const VERSION_URL = 'https://shorts-maker-omega.vercel.app/extension-blog/version.json';
const DEFAULT_STATE = { queue: [], settings: { autoDetect: true, autoPublish: false }, lastUpdateCheck: null, update: null };
async function getState() { const stored = await chrome.storage.local.get('moneyosBlogState'); return { ...DEFAULT_STATE, ...(stored.moneyosBlogState || {}) }; }
async function setState(state) { await chrome.storage.local.set({ moneyosBlogState: state }); return state; }
function id() { return `MONEYOS-${Date.now()}-${crypto.randomUUID().slice(0, 8)}`; }
async function activeTab() { const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); if (!tab?.id) throw new Error('활성 탭을 찾을 수 없습니다. GPT 탭을 열어 주세요.'); return tab; }
async function importPost(post) { if (post?.error) throw new Error(post.error); const state = await getState(); const existing = state.queue.find((item) => item.postId === post.postId); if (existing) return { ...existing, duplicate: true }; const item = { ...post, id: id(), status: '검수 대기', createdAt: new Date().toISOString(), results: {} }; state.queue.unshift(item); await setState(state); return item; }
async function checkForUpdate() { let storeResult = 'unavailable'; try { storeResult = await new Promise((resolve) => chrome.runtime.requestUpdateCheck((status) => resolve(status))); } catch {} const response = await fetch(`${VERSION_URL}?t=${Date.now()}`, { cache: 'no-store' }); if (!response.ok) throw new Error(`업데이트 정보 응답 오류 ${response.status}`); const remote = await response.json(); const current = chrome.runtime.getManifest().version; const available = storeResult === 'update_available' || Boolean(remote.version && remote.version !== current); const state = await getState(); state.lastUpdateCheck = new Date().toISOString(); state.update = { current, ...remote, available, storeResult }; await setState(state); return state.update; }
async function openEditor(itemId) { const state = await getState(); const item = state.queue.find((entry) => entry.id === itemId); if (!item) throw new Error('대기열 글을 찾을 수 없습니다.'); const tab = await chrome.tabs.create({ url: 'https://blog.naver.com/PostWriteForm.naver' }); const listener = async (tabId, changeInfo) => { if (tabId !== tab.id || changeInfo.status !== 'complete') return; chrome.tabs.onUpdated.removeListener(listener); await new Promise((resolve) => setTimeout(resolve, 1200)); try { const result = await chrome.tabs.sendMessage(tab.id, { type: 'MONEYOS_INSERT_POST', post: item }); const latest = await getState(); const target = latest.queue.find((entry) => entry.id === item.id); if (target) { target.status = result.ok ? '입력 완료·발행 확인 대기' : '입력 실패'; target.results = result; await setState(latest); } } catch (error) { const latest = await getState(); const target = latest.queue.find((entry) => entry.id === item.id); if (target) { target.status = '입력 실패'; target.results = { ok: false, error: error.message }; await setState(latest); } } }; chrome.tabs.onUpdated.addListener(listener); return tab.id; }
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => { (async () => { if (message.type === 'READ_CURRENT_GPT') { const tab = await activeTab(); const parsed = await chrome.tabs.sendMessage(tab.id, { type: 'MONEYOS_READ_GPT' }); sendResponse({ ok: true, post: await importPost(parsed) }); } else if (message.type === 'GET_STATE') { sendResponse({ ok: true, state: await getState(), version: chrome.runtime.getManifest().version }); } else if (message.type === 'DELETE_QUEUE_ITEM') { const state = await getState(); state.queue = state.queue.filter((item) => item.id !== message.id); await setState(state); sendResponse({ ok: true, state }); } else if (message.type === 'CHECK_UPDATE') { sendResponse({ ok: true, update: await checkForUpdate() }); } else if (message.type === 'OPEN_NAVER_EDITOR') { sendResponse({ ok: true, tabId: await openEditor(message.id) }); } else { sendResponse({ ok: false, error: '알 수 없는 메시지입니다.' }); } })().catch((error) => sendResponse({ ok: false, error: error.message })); return true; });
chrome.commands.onCommand.addListener(async (command) => { if (command !== 'read-current-gpt') return; try { await chrome.notifications.create({ type: 'basic', iconUrl: 'assets/icon-128.png', title: '머니OS', message: '확장프로그램 팝업에서 현재 GPT 글 읽기를 눌러 주세요.' }); } catch {} });
