const $ = (id) => document.getElementById(id);
async function send(type, extra = {}) { return chrome.runtime.sendMessage({ type, ...extra }); }
function esc(value) { return String(value ?? '').replace(/[&<>\\\"]/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '\\':'&#92;', '"':'&quot;' }[c])); }
function render(state, version) { $('version').textContent = `v${version}`; const queue = state.queue || []; $('count').textContent = queue.length; $('queue').innerHTML = queue.length ? queue.map((item) => `<article class="item"><b>${esc(item.title)}</b><div class="meta">${esc(item.status)} · ${esc((item.targets || []).join(', '))}</div><button data-delete="${esc(item.id)}">삭제</button><button data-open="${esc(item.id)}">네이버 작성</button></article>`).join('') : '<p class="meta">아직 읽은 글이 없습니다.</p>'; document.querySelectorAll('[data-delete]').forEach((button) => button.addEventListener('click', async () => { await send('DELETE_QUEUE_ITEM', { id: button.dataset.delete }); await refresh('삭제 완료'); })); document.querySelectorAll('[data-open]').forEach((button) => button.addEventListener('click', async () => { const result = await send('OPEN_NAVER_EDITOR', { id: button.dataset.open }); $('status').textContent = result.ok ? '네이버 글쓰기 탭에서 입력 중입니다.' : result.error; })); }
async function refresh(message = '준비됨') { const result = await send('GET_STATE'); if (!result.ok) throw new Error(result.error); render(result.state, result.version); $('status').textContent = message; }
$('read').addEventListener('click', async () => { $('status').textContent = 'GPT 글 읽는 중'; const result = await send('READ_CURRENT_GPT'); if (!result.ok) $('status').textContent = `오류: ${result.error}`; else await refresh(result.post.duplicate ? '이미 등록된 글입니다.' : 'GPT 글을 대기열에 등록했습니다.'); });
$('refresh').addEventListener('click', () => refresh('대기열 새로고침 완료').catch((e) => $('status').textContent = e.message));
$('update').addEventListener('click', async () => { $('status').textContent = '업데이트 확인 중'; const result = await send('CHECK_UPDATE'); if (!result.ok) { $('updateInfo').hidden = false; $('updateInfo').textContent = `업데이트 확인 실패: ${result.error}`; return; } const u = result.update; $('updateInfo').hidden = false; $('updateInfo').className = u.available ? 'notice' : 'notice ok'; $('updateInfo').textContent = u.available ? `새 버전 ${u.version}이 감지됐습니다. 정식 배포판은 브라우저가 자동 적용합니다.` : `최신 버전입니다. (${u.current})`; $('status').textContent = '업데이트 확인 완료'; });
$('reload').addEventListener('click', () => chrome.runtime.reload());
refresh().catch((e) => $('status').textContent = e.message);
