"use client";

import { useEffect, useMemo, useState } from "react";
import { runLoopTick, newLoopState, type LoopState } from "@/lib/jevLoopEngine";

type Candle = { trade_price: number; opening_price?: number; high_price?: number; low_price?: number; candle_acc_trade_volume?: number; candle_date_time_kst?: string };
type Unit = { ask_price: number; bid_price: number; ask_size: number; bid_size: number };
type Market = { market: string; korean_name: string; price?: number; change?: number; volume?: number };
type Payload = { ok: boolean; price?: number; candles?: Candle[]; orderbook?: { units: Unit[] }; error?: string };

const won = (n = 0) => Math.round(n).toLocaleString("ko-KR");
const commonMarkets = ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-SOL", "KRW-DOGE", "KRW-ADA", "KRW-AVAX", "KRW-LINK", "KRW-DOT", "KRW-TRX"];

function Chart({ candles, price, onHover }: { candles: Candle[]; price?: number; onHover: (candle: Candle | null) => void }) {
  const ordered = candles.slice(0, 100).reverse();
  const [hover, setHover] = useState<number | null>(null);
  const lows = ordered.map((c) => Number(c.low_price ?? c.trade_price)); const highs = ordered.map((c) => Number(c.high_price ?? c.trade_price));
  const min = Math.min(...lows, price || Infinity); const max = Math.max(...highs, price || -Infinity); const span = Math.max(max - min, 1);
  const maxVol = Math.max(...ordered.map((c) => Number(c.candle_acc_trade_volume ?? 0)), 1);
  const px = (i: number) => 18 + (i / Math.max(ordered.length - 1, 1)) * 760;
  const py = (v: number) => 245 - ((v - min) / span) * 190;
  const avg = (period: number) => ordered.map((c, i) => i < period - 1 ? null : `${px(i)},${py(ordered.slice(i - period + 1, i + 1).reduce((s, x) => s + Number(x.trade_price), 0) / period)}`).filter(Boolean).join(" ");
  const setPoint = (e: React.MouseEvent<SVGSVGElement>) => { const rect = e.currentTarget.getBoundingClientRect(); const index = Math.round(((e.clientX - rect.left) / rect.width) * (ordered.length - 1)); setHover(Math.max(0, Math.min(ordered.length - 1, index))); onHover(index >= 0 ? ordered[index] : null); };
  return <div className="relative h-full min-h-[300px] w-full overflow-hidden bg-[#0d1117]">
    <svg viewBox="0 0 800 300" className="h-full w-full" preserveAspectRatio="none" onMouseMove={setPoint} onMouseLeave={() => { setHover(null); onHover(null); }}>
      <g stroke="#24303b" strokeWidth="0.7">{[35, 85, 135, 185, 235].map((y) => <line key={y} x1="0" x2="800" y1={y} y2={y} />)}{[100, 220, 340, 460, 580, 700].map((x) => <line key={x} y1="0" y2="270" x1={x} x2={x} />)}</g>
      {ordered.map((c, i) => { const o = Number(c.opening_price ?? c.trade_price); const cl = Number(c.trade_price); const hi = Number(c.high_price ?? Math.max(o, cl)); const lo = Number(c.low_price ?? Math.min(o, cl)); const up = cl >= o; const w = Math.max(3, 680 / ordered.length); return <g key={`${i}-${c.candle_date_time_kst}`}><line x1={px(i)} x2={px(i)} y1={py(hi)} y2={py(lo)} stroke={up ? "#2f8cff" : "#ef4444"} strokeWidth="1" /><rect x={px(i) - w / 2} y={Math.min(py(o), py(cl))} width={w} height={Math.max(1, Math.abs(py(o) - py(cl)))} fill={up ? "#2f8cff" : "#ef4444"} /><rect x={px(i) - w / 2} y={275 - (Number(c.candle_acc_trade_volume ?? 0) / maxVol) * 32} width={w} height={(Number(c.candle_acc_trade_volume ?? 0) / maxVol) * 32} fill={up ? "#2f8cff66" : "#ef444466"} /></g>; })}
      <polyline points={avg(5)} fill="none" stroke="#f7c948" strokeWidth="1.4" /><polyline points={avg(20)} fill="none" stroke="#b06cff" strokeWidth="1.4" />
      {hover !== null && <><line x1={px(hover)} x2={px(hover)} y1="0" y2="270" stroke="#aab4c0" strokeDasharray="3 3" /><line x1="0" x2="800" y1={py(Number(ordered[hover].trade_price))} y2={py(Number(ordered[hover].trade_price))} stroke="#aab4c0" strokeDasharray="3 3" /><rect x={Math.min(px(hover) + 4, 650)} y="6" width="135" height="28" fill="#161d25" stroke="#3b4754" /><text x={Math.min(px(hover) + 10, 656)} y="18" fill="#d7dee7" fontSize="9">{won(Number(ordered[hover].trade_price))}원</text><text x={Math.min(px(hover) + 10, 656)} y="29" fill="#8793a1" fontSize="8">{ordered[hover].candle_date_time_kst?.slice(11, 16) || "실시간"}</text></>}
    </svg>
    <div className="absolute bottom-1 left-2 text-[10px] text-zinc-500">파랑 상승 · 빨강 하락 · 노랑 최근 평균 · 보라 긴 평균 · 거래량 막대</div>
  </div>;
}

export function TraderWorkspace({ mode }: { mode: "paper" | "live" }) {
  const [market, setMarket] = useState("KRW-BTC"); const [markets, setMarkets] = useState<Market[]>(commonMarkets.map((m) => ({ market: m, korean_name: m.replace("KRW-", "") })));
  const [data, setData] = useState<Payload | null>(null); const [prices, setPrices] = useState<Record<string, number>>({}); const [flash, setFlash] = useState<string | null>(null);
  const [status, setStatus] = useState("실시간 연결 준비"); const [hovered, setHovered] = useState<Candle | null>(null); const [loop, setLoop] = useState<LoopState>(() => newLoopState()); const [notice, setNotice] = useState("모의매매는 실시간 업비트 데이터에 맞춰 지정가 체결을 시뮬레이션합니다");

  const load = async (code = market) => { try { const r = await fetch(`/api/coin/market?market=${code}`, { cache: "no-store" }); const p = await r.json() as Payload; if (!p.ok) throw new Error(p.error || "[MARKET_DATA_ERROR] 업비트 캔들·호가 응답이 비어 있습니다"); setData(p); } catch (e) { setNotice(e instanceof Error ? e.message : "[MARKET_DATA_ERROR] 업비트 시세 조회 단계에서 원인을 확인할 수 없습니다"); } };
  useEffect(() => { void load(); void fetch("/api/coin/markets", { cache: "no-store" }).then((r) => r.json()).then((x) => { if (x.ok && x.markets?.length) setMarkets(x.markets); }).catch(() => setNotice("[MARKET_LIST_ERROR] 업비트 코인 목록 조회 단계에서 연결에 실패했습니다")); }, []);
  useEffect(() => { void load(market); }, [market]);
  useEffect(() => { const ws = new WebSocket("wss://api.upbit.com/websocket/v1"); ws.onopen = () => { setStatus("● 실시간 수신 중"); ws.send(JSON.stringify([{ ticket: "moneyos-upbit-trader" }, { type: "ticker", codes: markets.map((m) => m.market), format: "DEFAULT" }, { type: "orderbook", codes: [market], format: "DEFAULT" }])); }; ws.onmessage = async (e) => { try { const text = typeof e.data === "string" ? e.data : new TextDecoder().decode(await e.data.arrayBuffer()); const x = JSON.parse(text); if (x.type === "ticker") { const code = x.code as string; setPrices((p) => ({ ...p, [code]: Number(x.trade_price) })); setFlash(code); window.setTimeout(() => setFlash((f) => f === code ? null : f), 260); if (code === market) { setData((p) => p ? { ...p, price: Number(x.trade_price), candles: p.candles?.map((c, i) => i === 0 ? { ...c, trade_price: Number(x.trade_price) } : c) } : p); setStatus(`● 실시간 수신 ${new Date().toLocaleTimeString("ko-KR")}`); } } else if (x.type === "orderbook" && x.code === market) setData((p) => p ? { ...p, orderbook: { units: x.orderbook_units?.slice(0, 12) || [] } } : p); } catch { setNotice("[UPBIT_WS_PARSE_ERROR] 실시간 티커·호가 데이터 해석 단계에서 업비트 응답 형식이 달라졌습니다"); } }; ws.onerror = () => { setStatus("○ 실시간 오류"); setNotice("[UPBIT_WS_CONNECTION_ERROR] 업비트 WebSocket 연결 단계에서 실시간 수신이 중단되었습니다"); }; return () => ws.close(); }, [market, markets]);
  const tick = () => { if (!data?.price || !data.orderbook?.units?.[0]) return setNotice("[JEV_TICK_BLOCKED] 현재가·최우선 호가가 없어 판단 루프를 실행하지 않았습니다"); const u = data.orderbook.units[0]; const result = runLoopTick(loop, { price: data.price, prices: data.candles?.map((c) => Number(c.trade_price)).reverse() || [], bestAsk: u.ask_price, bestBid: u.bid_price, askSize: u.ask_size, bidSize: u.bid_size, websocketHealthy: true, dataAgeMs: 0, allowedBuy: true, allowedSell: true }); setLoop(result.state); setNotice(`[JEV ${result.action}] ${result.decisionReason}${result.fills.length ? ` · ${result.fills.length}건 지정가 체결` : " · 아직 체결 없음"}`); };
  const units = data?.orderbook?.units || []; const current = data?.price || prices[market];
  const selected = hovered || data?.candles?.[0];
  return <div className="flex h-[min(88vh,920px)] min-h-[620px] w-full min-w-0 flex-col overflow-hidden border-2 border-[#39434e] bg-[#0b0e11] text-[11px] text-zinc-200">
    <div className="flex flex-wrap items-center gap-2 border-b border-[#2b333c] bg-[#151a20] px-3 py-2"><b className="mr-2 text-sm text-white">{mode === "paper" ? "모의매매원" : "실제매매원"}</b><span className={mode === "paper" ? "text-amber-400" : "text-red-400"}>{mode === "paper" ? "PAPER · 실시간 지정가 체결" : "LIVE · 3단계 승인 잠금"}</span><span className="text-emerald-400">{status}</span><div className="ml-auto flex gap-1 text-zinc-400"><button className="border border-zinc-700 px-2 py-1">1분</button><button className="border border-zinc-700 px-2 py-1">5분</button><button className="border border-zinc-700 px-2 py-1">15분</button><button className="border border-zinc-700 px-2 py-1">지표</button><button className="border border-zinc-700 px-2 py-1">전체화면</button></div></div>
    <div className="grid min-h-0 flex-1 grid-cols-1 lg:grid-cols-[minmax(0,1fr)_250px_220px]">
      <section className="flex min-h-0 min-w-0 flex-col border-b border-[#2b333c] lg:border-b-0 lg:border-r"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-[#2b333c] px-3 py-2"><div><b className="text-white">{market.replace("KRW-", "")} / KRW</b><span className="ml-2 text-zinc-500">1분 · UPBIT</span>{selected && <span className="ml-3 text-sky-300">시 {won(Number(selected.opening_price))} 고 {won(Number(selected.high_price))} 저 {won(Number(selected.low_price))} 종 {won(Number(selected.trade_price))}</span>}</div><div className="text-right"><b className="text-base text-white">{won(current)}원</b><span className="ml-2 text-zinc-500">거래량 {won(Number(data?.candles?.[0]?.candle_acc_trade_volume || 0))}</span></div></div><div className="flex min-h-0 flex-1"><div className="hidden w-9 flex-col items-center gap-4 border-r border-[#2b333c] py-3 text-zinc-500 sm:flex"><span>＋</span><span>╱</span><span>⌁</span><span>♢</span><span>⌕</span><span>Ｔ</span><span>◉</span><span>＋</span></div><div className="min-h-[320px] min-w-0 flex-1"><Chart candles={data?.candles || []} price={current} onHover={setHovered} /></div></div><div className="flex flex-wrap gap-3 border-t border-[#2b333c] px-3 py-2 text-zinc-500"><span>30일</span><span>5일</span><span>1일</span><span className="ml-auto">UTC+9</span><span>％</span><span>로그</span><span className="text-sky-400">자동</span></div></section>
      <section className="flex min-h-0 flex-col border-b border-[#2b333c] lg:border-b-0 lg:border-r"><div className="border-b border-[#2b333c] px-3 py-2 text-zinc-400">호가 · {market}</div><div className="grid grid-cols-2 px-3 py-1 text-right text-[10px] text-zinc-600"><span>매도 수량 / 가격</span><span>가격 / 매수 수량</span></div><div className="min-h-0 flex-1 overflow-auto">{units.map((u, i) => <div key={`${u.ask_price}-${i}`} className="grid grid-cols-2 border-b border-[#171d23] text-right"><span className="bg-red-950/20 px-2 py-1 text-red-300">{u.ask_size.toFixed(4)}<br />{won(u.ask_price)}</span><span className="bg-blue-950/20 px-2 py-1 text-sky-300">{won(u.bid_price)}<br />{u.bid_size.toFixed(4)}</span></div>)}</div><div className="grid grid-cols-2 gap-2 p-3"><button onClick={tick} className="border border-emerald-700 bg-emerald-950/30 px-2 py-2 text-emerald-300">JEV 매수판단</button><button onClick={tick} className="border border-red-700 bg-red-950/30 px-2 py-2 text-red-300">JEV 매도판단</button></div><div className="border-t border-[#2b333c] p-3 text-zinc-500">JEV 상태: <b className="text-amber-300">{loop.tick ? `${loop.tick}틱 · ${loop.resting.length}개 대기` : "대기"}</b><br />체결: {loop.fills.length}건 · 실현손익: {won(loop.realizedPnl)}원</div></section>
      <section className="flex min-h-0 flex-col"><div className="border-b border-[#2b333c] px-3 py-2 text-zinc-400">코인목록 · 현재가 · 거래대금</div><div className="grid grid-cols-[1fr_75px_60px] px-2 py-1 text-[10px] text-zinc-600"><span>코인</span><span className="text-right">현재가</span><span className="text-right">변동</span></div><div className="min-h-0 flex-1 overflow-auto">{markets.map((m) => { const p = prices[m.market]; return <button key={m.market} onClick={() => setMarket(m.market)} className={`grid w-full grid-cols-[1fr_75px_60px] border-b border-[#171d23] px-2 py-2 text-left hover:bg-[#1a222b] ${market === m.market ? "bg-[#202b36]" : ""} ${flash === m.market ? "animate-pulse bg-amber-950/50" : ""}`}><span><b className="block text-zinc-200">{m.market.replace("KRW-", "")}</b><small className="text-zinc-600">{m.korean_name}</small></span><span className="text-right text-zinc-200">{p ? won(p) : "-"}</span><span className={`text-right ${Number(m.change) >= 0 ? "text-red-400" : "text-blue-400"}`}>{m.change == null ? "-" : `${Number(m.change) >= 0 ? "+" : ""}${(Number(m.change) * 100).toFixed(2)}%`}</span></button>; })}</div></section>
    </div><div className={`border-t px-3 py-2 ${notice.includes("[") ? "border-red-900 bg-red-950/20 text-red-300" : "border-[#2b333c] text-zinc-500"}`}>{notice}</div>{mode === "live" && <div className="border-t border-red-900 bg-red-950/20 px-3 py-2 text-red-300">실제 주문 잠금: ① 승인관리 ② 리스크관리 ③ 블랙 최종승인과 서버 게이트 확인 전에는 주문 API를 호출하지 않습니다</div>}</div>;
}
