"use client";
import {useCallback,useEffect,useState} from 'react';
type Rule={version?:number;id:string;category:string;text:string};
type Policy={scanner?:Record<string,number>;revision:number;rules:Rule[];sizing:{minPct:number;maxPct:number;riskPct:number}};
const names:Record<string,string>={selection:'종목선정',entry:'Jev 매수근거',exit:'Jev 매도근거',trend:'가격흐름',flow:'거래량·매수세',liquidity:'호가·체결',sizing:'투자비용',risk:'위험관리'};
const help:Record<string,string>={selection:'전체 원화 종목을 동시에 감시해 이미 급등한 1위를 추격하지 않고, 거래대금·매수세·호가가 가격보다 먼저 좋아지는 PRE_SETUP/SETUP 후보를 미리 고릅니다. ENTRY_READY 전에는 Jev를 호출하지 않고 자료만 축적합니다.',entry:'종목·가격·매수세·호가·위험 근거를 분야별 같은 비중으로 합칩니다. 설정된 진입 점수 이상이고 자료 부족·위험 반대가 없을 때 매수합니다.',exit:'아래 매도근거 중 하나가 설정된 매도 판단 기준을 넘으면 청산을 시작합니다. 체결과 잔량 확인이 끝나야 다음 종목으로 갑니다.',trend:'단기 평균은 최근 가격 흐름을 부드럽게 보여주는 선입니다. 돌파·눌림 등 추가 근거를 입력할 수 있습니다.',flow:'최근 거래대금과 실제 매수 체결 비중을 사용합니다. 단순 호가 잔량과 실제 체결은 구분합니다.',liquidity:'원하는 가격에 사고팔 물량이 있는지 확인합니다. 주문 전 실제 잔액·수수료·호가를 다시 검사합니다.',sizing:'주문가능 원화에 판단 비율을 곱한 뒤 최대 보유·수수료·손실 예산·보이는 호가 물량 제한 중 가장 작은 금액을 사용합니다. 기본 비율은 검증 전 연구 설정이며 수익 확률이 아닙니다.',risk:'아래 항목은 Jev가 신규 매수 위험을 판단하는 근거입니다. 손절·계좌 손실·인증 같은 필수 제한은 아래 별도 표시하며 문장 삭제로 해제되지 않습니다.'};
export function TradingEvidencePanel({asset,category}:{asset:'coin'|'stock';category:string}){
 const [policy,setPolicy]=useState<Policy|null>(null),[text,setText]=useState(''),[message,setMessage]=useState('불러오는 중…'),[busy,setBusy]=useState(false),[auth,setAuth]=useState(false),[key,setKey]=useState(''),[status,setStatus]=useState(''),[limits,setLimits]=useState<Record<string,Record<string,number>>|null>(null);
 const load=useCallback(async()=>{try{const r=await fetch('/api/trading/evidence?asset='+asset,{cache:'no-store'});const j=await r.json();if(r.status===401){setAuth(true);setMessage('매매 인증키로 이 브라우저를 먼저 등록하세요.');return;}if(!r.ok)throw Error(j.error||'근거 조회 실패');setPolicy(j.policy);setStatus(j.status);setAuth(false);setMessage('저장된 근거 버전 '+j.policy.revision);if(asset==='coin'){const pairs=await Promise.all(['paper','live'].map(async mode=>{const w=await fetch('/api/coin/terminal/worker?mode='+mode);return [mode,w.ok?(await w.json()).engine.config:null] as const;}));setLimits(Object.fromEntries(pairs.filter(([,v])=>v)));}}catch(e){setMessage(e instanceof Error?e.message:'근거 조회 실패: 서버 응답을 확인하세요.');}finally{setBusy(false);}},[asset]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
 async function register(){setBusy(true);try{const r=await fetch('/api/coin/terminal/auth',{method:'POST',headers:{'x-trading-operator':key}});if(!r.ok)throw Error('브라우저 등록 실패: 인증키를 확인하세요.');setKey('');await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function save(next:Policy){setBusy(true);try{const r=await fetch('/api/trading/evidence?asset='+asset,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({policy:next,revision:policy?.revision})});const j=await r.json();if(!r.ok)throw Error(j.error||'근거 저장 실패');setPolicy(j.policy);setStatus(j.status);setText('');setMessage(asset==='coin'?'저장 완료 · 모의·실전 다음 판단부터 같은 버전 적용':'저장 완료 · 주식 모의·실전 엔진 연결 대기');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const list=policy?.rules.filter(r=>r.category===category)||[];
 return <section className="flex min-h-0 flex-col gap-4 overflow-y-auto p-2 text-sm text-zinc-200" aria-label={names[category]+' 근거 관리'}>
 <div className="rounded border border-blue-900 bg-blue-950/30 p-3"><b>{asset==='coin'?'코인':'주식'} · {names[category]}</b><p className="mt-2 text-xs text-zinc-400">{help[category]}</p><p className="mt-2 text-xs text-blue-300">{status}</p></div>
 {auth?<div className="flex flex-wrap gap-2"><input aria-label="매매 인증키" type="password" value={key} onChange={e=>setKey(e.target.value)} className="min-w-0 flex-1 rounded bg-zinc-900 p-2"/><button disabled={busy||!key} onClick={register}>브라우저 등록</button></div>:null}
 {policy&&<><ul className="space-y-2">{list.map(r=><li key={r.id} className="flex items-start gap-2 rounded border border-zinc-700 bg-zinc-900 p-3"><span className="flex-1 break-words"><small className="block text-zinc-500">{r.id} v{r.version||1}</small>{r.text}</span><button aria-label={'근거 삭제: '+r.text} title="이 근거를 모의·실전 공통 목록에서 삭제" disabled={busy} onClick={()=>save({...policy,rules:policy.rules.filter(x=>x.id!==r.id)})} className="px-2 text-lg text-red-300">×</button></li>)}</ul>{!list.length&&<p className="text-amber-300">등록된 근거가 없습니다. 매수근거·투자비용이 비어 있으면 자동 신규 매수를 보류합니다.</p>}
 <form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();if(text.trim())void save({...policy,rules:[...policy.rules,{id:'r_'+crypto.randomUUID().replaceAll('-',''),category,text:text.trim()}]});}}><input aria-label="추가할 매매 근거" maxLength={300} value={text} onChange={e=>setText(e.target.value)} placeholder="추가할 판단 근거를 한 줄로 입력하세요" className="min-w-[180px] flex-1 rounded border border-zinc-700 bg-zinc-900 p-3"/><button disabled={busy||!text.trim()||policy.rules.length>=40} className="rounded bg-blue-600 px-4 py-2 disabled:opacity-40">근거 추가</button></form>
 <p className="text-xs text-zinc-500">입력한 문장은 코드가 아닌 판단 기준입니다. 필요한 데이터가 없으면 자료 부족으로 처리합니다. 삭제는 즉시 저장됩니다. 근거 수가 늘면 같은 1회 호출의 사용량은 늘 수 있습니다.</p>
 {category==='selection'&&policy.scanner&&<div className="space-y-2 rounded border border-zinc-700 p-3"><b>전 종목 감시 V2 · 연구 설정</b><p className="text-xs text-amber-300">점수는 수익 확률이 아닙니다. 이벤트 판단은 60초 정기 판단 외 추가 API 사용량을 만들 수 있습니다.</p>{Object.entries({trendWeight:'초입 가격흐름 비중',flowWeight:'선행 거래량·매수세 비중',liquidityWeight:'호가 비중',warmingScore:'PRE_SETUP 점수',candidateScore:'SETUP 점수',readyScore:'ENTRY_READY 점수',eventCooldownSeconds:'같은 종목 Jev 재판단 최소 간격 (초)',globalCooldownSeconds:'전체 Jev 추가 판단 최소 간격 (초)',stableSeconds:'후보 유지 확인 (초)',switchMargin:'선행 후보 교체 점수 차이',maxRiseBps:'과열 차단 기준 (100 = 1%)',maxVwapGapBps:'과열 VWAP 이격 차단 (100 = 1%)',maxEntryRiseBps:'신규진입 60초 상승 상한 (100 = 1%)',maxEntryVwapGapBps:'신규진입 VWAP 이격 상한 (100 = 1%)',maxFastRiseBps:'신규진입 5초 급등 상한 (100 = 1%)',minBuyShare:'최소 매수체결 비중 (0.55 = 55%)',minTurnoverGrowth:'최소 거래대금 증가배수'}).map(([k,label])=><label key={k} className="flex flex-wrap justify-between gap-2 text-xs">{label}<input aria-label={label} type="number" value={policy.scanner?.[k]??0} onChange={e=>setPolicy({...policy,scanner:{...policy.scanner,[k]:Number(e.target.value)}})} className="w-24 rounded bg-zinc-800 p-2"/></label>)}<button disabled={busy} onClick={()=>save(policy)} className="rounded bg-blue-600 p-2">시장 감시 설정 저장 · 모의/실전 공통</button></div>}
 {category==='sizing'&&<div className="space-y-3 rounded border border-zinc-700 p-3">{([['minPct','최소 목표 투자 비율 (%)'],['maxPct','최대 목표 투자 비율 (%)'],['riskPct','1회 손실 예산 · 운용금 대비 (%)']] as const).map(([k,label])=><label key={k} className="flex flex-wrap items-center justify-between gap-2">{label}<input type="number" aria-label={label} step="0.05" min={k==='riskPct'?0.05:1} max={k==='riskPct'?2:100} value={policy.sizing[k]} onChange={e=>setPolicy({...policy,sizing:{...policy.sizing,[k]:Number(e.target.value)}})} className="w-24 rounded bg-zinc-800 p-2"/></label>)}<button disabled={busy} onClick={()=>save(policy)} className="rounded bg-blue-600 px-3 py-2">투자 비율 저장 · 모의/실전 공통</button><p className="text-xs text-amber-300">한도에 걸리면 최소 목표 비율보다 작아질 수 있습니다. 최소 주문 미만이면 매수하지 않습니다. 손절 가격은 실제 체결 보장이 아닙니다.</p></div>}
 <details className="rounded border border-zinc-700 p-3"><summary>항상 적용되는 주문 제한과 기본 계산 보기</summary><ul className="mt-3 list-disc space-y-2 pl-5 text-xs text-zinc-400"><li>인증·잔액·수수료·최소 주문·미확정 주문 확인, 중복 주문 차단</li><li>보유·부분 체결·취소 확인·잔여 청산이 있으면 종목 유지</li><li>가격 흐름·매수 체결·호가 점수를 합쳐 후보를 찾습니다. 순위 1위 여부는 매수 조건이 아닙니다. 아래 숫자는 검증 전 연구 설정이며 실제 PAPER 결과로 조정합니다.</li><li>손절, 계좌 손실, 최근 급락 및 변동폭 추적 손절은 Jev와 별개로 감시</li>{(['paper','live'] as const).map(mode=><li key={mode}>{mode==='paper'?'모의':'실전'}: 최대 보유 {limits?.[mode]?limits[mode].maxPositionKrw.toLocaleString()+'원':'연결 후 확인'} · 일일 손실 {limits?.[mode]?limits[mode].dailyLossKrw.toLocaleString()+'원':'연결 후 확인'} · 손절 {limits?.[mode]?limits[mode].stopLossPct+'%':'연결 후 확인'}</li>)}<li>최대 보유·손실·호가 제한은 각 모의/실전 매매원의 연결·전략 설정에서 수정</li><li>추가 뉴스·외부 지표 데이터는 문장만 입력해도 자동 연결되는 것이 아닙니다.</li></ul></details></>}
 <div role="status" className="break-words text-xs text-amber-200">{message}</div><button disabled={busy} onClick={load} className="self-start text-xs text-blue-300">새로 불러오기</button></section>;
}
