"use client";
import {useCallback,useEffect,useState} from 'react';
type Row={id:string;mode:string;market:string;opened:number;closed:number|null;realized:number;return_pct:number|null;held_ms:number};
type Status={state:string;collection:string;total:number;lastData:number|null;lastAnalysis:number|null;error?:string|null;bytes?:number;pending?:number};
type Result={rows:Row[];total:number;status:Status;note?:string};
type Report={count:number;wins:number;losses:number;realized:number;average:number|null;byEvidence:{key:string;trades:number;losses:number;pnl:number}[];byCause:{cause:string;trades:number}[];caution:string};
type Evidence={staff:string;id:string;version:number;text:string;status:string;support:number|null};
type Detail={fills:{id:string;side:string;at:number;quantity:string;funds:string;fee:string;realized:string;cause:string;context:{reason:string;evidence:Evidence[]};window:{status:string;count:number;expected:number}}[];samples:unknown[]};
const won=(n:number)=>n.toLocaleString('ko-KR',{maximumFractionDigits:2})+'원';
const date=(n:number|null)=>n?new Date(n).toLocaleString('ko-KR'):'기록 없음';
const causes:Record<string,string>={jev:'Jev 판단',hard_stop:'하드 손절',risk:'위험관리',manual:'사용자 수동 주문',strategy_exit:'일반 전략 청산',system:'기타 시스템',legacy_unknown:'도입 이전 · 원인 미확인'};
export function TradingAnalyticsPanel({asset}:{asset:'coin'|'stock'}){
 const [query,setQuery]=useState<Record<string,string>>({days:'7',mode:'paper',outcome:''}),[data,setData]=useState<Result|null>(null),[report,setReport]=useState<Report|null>(null),[detail,setDetail]=useState<Detail|null>(null),[message,setMessage]=useState('조회 준비'),[busy,setBusy]=useState(false),[auth,setAuth]=useState(false),[key,setKey]=useState('');
 const params=useCallback(()=>{const {days,...rest}=query;return {asset,...Object.fromEntries(Object.entries(rest).filter(([,v])=>v)),from:String(Date.now()-Number(days)*86400000),to:String(Date.now())};},[asset,query]);
 const load=useCallback(async()=>{setBusy(true);try{const r=await fetch('/api/trading/analytics?'+new URLSearchParams(params()),{cache:'no-store'}),j=await r.json();if(r.status===401){setAuth(true);setMessage('매매 인증키로 이 브라우저를 등록하면 분석 자료를 볼 수 있습니다.');return;}if(!r.ok)throw Error(j.error);setAuth(false);setData(j);setMessage(j.note||'조회 완료');}catch(e){setMessage('분석 조회: '+(e as Error).message);}finally{setBusy(false);}},[params]);
 useEffect(()=>{const t=setTimeout(()=>{setReport(null);setDetail(null);void load();},0);return()=>clearTimeout(t);},[load]);
 async function register(){try{const r=await fetch('/api/coin/terminal/auth',{method:'POST',headers:{'x-trading-operator':key}});if(!r.ok){const j=await r.json();throw Error(j.error||'인증키를 확인하세요.');}setKey('');await load();}catch(e){setMessage('브라우저 등록: '+(e as Error).message);}}
 async function analyze(){setBusy(true);try{const r=await fetch('/api/trading/analytics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(params())}),j=await r.json();if(!r.ok)throw Error(j.error);setReport(j);await load();}catch(e){setMessage('리포트 생성: '+(e as Error).message);}finally{setBusy(false);}}
 async function open(id:string){setBusy(true);try{const r=await fetch('/api/trading/analytics?'+new URLSearchParams({asset,id})),j=await r.json();if(!r.ok)throw Error(j.error);setDetail(j);}catch(e){setMessage('거래 상세: '+(e as Error).message);}finally{setBusy(false);}}
 function download(){const blob=new Blob([JSON.stringify({query:params(),data,report,detail},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='trading-analysis.json';a.click();URL.revokeObjectURL(url);}
 return <section aria-label="매매분석" className="flex min-h-0 flex-col gap-3 overflow-y-auto text-sm text-zinc-200">
 <p className="rounded border border-zinc-700 p-3">거래 당시 근거와 시장 흐름을 기록합니다. 주문하거나 근거를 자동 수정하지 않습니다. {asset==='stock'&&'주식 주문 엔진 연결 대기 · 실제 수집 없음'}</p>
 {auth&&<div className="flex gap-2"><input aria-label="매매 인증키" type="password" value={key} onChange={e=>setKey(e.target.value)} className="min-w-0 flex-1 bg-zinc-800 p-2"/><button onClick={register} disabled={!key}>브라우저 등록</button></div>}
 {data&&<div className="grid grid-cols-2 gap-2 rounded bg-zinc-900 p-3 sm:grid-cols-3"><span>상태: {busy?'업무중':data.status.state}</span><span>데이터 수집: {data.status.collection}</span><span>누적 거래: {data.status.total.toLocaleString()}건</span><span>최근 데이터: {date(data.status.lastData)}</span><span>최근 분석: {date(data.status.lastAnalysis)}</span><span>저장량: {((data.status.bytes||0)/1048576).toFixed(2)} MB</span>{data.status.error&&<p role="alert" className="col-span-full text-red-300">{data.status.error}</p>}</div>}
 <div className="flex flex-wrap gap-2"><select aria-label="조회 기간" value={query.days} onChange={e=>setQuery({...query,days:e.target.value})} className="bg-zinc-800 p-2"><option value="1">최근 1일</option><option value="7">최근 7일</option><option value="30">최근 30일</option><option value="365">최근 1년</option></select><select aria-label="분석 매매 모드" value={query.mode} onChange={e=>setQuery({...query,mode:e.target.value})} className="bg-zinc-800 p-2"><option value="paper">모의</option><option value="live">실전</option></select><select aria-label="손익 필터" value={query.outcome} onChange={e=>setQuery({...query,outcome:e.target.value})} className="bg-zinc-800 p-2"><option value="">전체 거래</option><option value="profit">수익 거래</option><option value="loss">손실 거래</option><option value="open">보유 중</option></select><select aria-label="청산 원인" value={query.cause||''} onChange={e=>setQuery({...query,cause:e.target.value})} className="bg-zinc-800 p-2"><option value="">모든 청산 원인</option>{Object.entries(causes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
 <details><summary>종목·직원·근거·수익률 조건</summary><div className="mt-2 grid grid-cols-2 gap-2">{[['market','종목 (KRW-BTC)'],['staff','직원명'],['rule','근거 ID'],['version','근거 버전'],['buyReason','매수 사유'],['sellReason','매도 사유'],['minReturn','최소 수익률 (%)'],['maxReturn','최대 수익률 (%)']].map(([k,label])=><input key={k} aria-label={label} placeholder={label} value={query[k]||''} onChange={e=>setQuery({...query,[k]:e.target.value})} className="min-w-0 bg-zinc-800 p-2"/>)}</div></details>
 <div className="flex flex-wrap gap-3"><button disabled={busy} onClick={load}>새로 조회</button><button disabled={busy||auth||asset==='stock'} onClick={analyze} className="rounded bg-blue-700 p-2">이 범위 리포트 생성</button><button disabled={!data} onClick={download}>조회 자료 JSON 저장</button></div>
 <p role="status" className="text-xs text-amber-200">{message}</p>
 {data&&<><p>조회 {data.rows.length} / {data.total}건 · 기본 최대 100건, 많은 자료는 기간을 좁혀주세요.</p><div className="overflow-x-auto"><table className="w-full whitespace-nowrap text-left text-xs"><thead><tr>{['매수 시각','종목','매도 시각','실현손익','수익률','상세'].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{data.rows.map(r=><tr key={r.id} className="border-t border-zinc-800"><td className="p-2">{date(r.opened)}</td><td>{r.market}</td><td>{r.closed?date(r.closed):'보유 중'}</td><td>{won(r.realized)}</td><td>{r.return_pct?.toFixed(2)??'미확인'}%</td><td><button onClick={()=>open(r.id)} className="text-blue-300">판단 과정</button></td></tr>)}</tbody></table></div></>}
 {report&&<div className="space-y-2 rounded border border-zinc-700 p-3"><b>분석 리포트</b><p>{report.count}건 · {report.wins}승 / {report.losses}패 · 실현손익 {won(report.realized)} · 평균 {report.average===null?'자료 없음':won(report.average)}</p>{report.byEvidence.map(r=><p key={r.key} className="text-xs">{r.key}: {r.trades}건 중 손실 {r.losses}건 · 연관 손익 {won(r.pnl)}</p>)}{report.byCause.map(r=><p key={r.cause}>{causes[r.cause]||r.cause}: {r.trades}건</p>)}<p className="text-xs text-amber-300">{report.caution}</p></div>}
 {detail&&<div className="space-y-3 rounded border border-zinc-700 p-3"><b>거래 당시 판단 과정</b>{detail.fills.map(f=><div key={f.id} className="border-t border-zinc-700 pt-2"><p>{f.side==='buy'?'매수':'매도'} · {date(f.at)} · {won(Number(f.funds))} · 수수료 {won(Number(f.fee))}</p><p>{causes[f.cause]||f.cause} · {f.context.reason}</p><p className="text-xs">전후 시장 자료: {f.window.status} ({f.window.count}/{f.window.expected})</p>{f.context.evidence.map(r=><p key={r.id} className="mt-1 text-xs text-zinc-400">{r.staff} / {r.id} v{r.version} · {r.status==='supported'?'충족':r.status==='opposed'?'반대':'자료 부족'} {r.support===null?'':(r.support*100).toFixed(1)+'%'} · {r.text}</p>)}</div>)}<p className="text-xs">중복 제거된 시세 {detail.samples.length}개 · JSON 저장에 포함</p></div>}
 </section>;
}
