"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { newLoopState, type LoopState } from "@/lib/jevLoopEngine";

type Candle = { trade_price: number; opening_price?: number; high_price?: number; low_price?: number; candle_acc_trade_volume?: number; candle_date_time_kst?: string };
type Unit = { ask_price: number; bid_price: number; ask_size: number; bid_size: number };
type Market = { market: string; korean_name: string; price?: number; change?: number; volume?: number };
type Payload = { ok: boolean; price?: number; candles?: Candle[]; orderbook?: { units: Unit[] }; error?: string };
type TickResponse = { ok: boolean; message?: string; error?: string; code?: string; jev?: { action: string; provider: string; confidence: number; probabilities: Record<string, number>; latencyMs: number; errorCode?: string; errorMessage?: string }; result?: { state: LoopState; action: string; battery: { provider: string; direction: string; buyConfidence: number; sellConfidence: number; latencyMs: number }; fills: unknown[]; orders: unknown[]; decisionReason: string } };
type AccountPayload = { ok: boolean; cash?: number; tradingValue?: number; pnl?: number; updatedAt?: string; error?: string };
type TickMeta = { action: string; provider: string; latencyMs: number; fills: number; orders: number; eventSeq: number };

const won = (n = 0) => Math.round(n).toLocaleString("ko-KR");
const commonMarkets = ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-SOL", "KRW-DOGE", "KRW-ADA", "KRW-AVAX", "KRW-LINK", "KRW-DOT", "KRW-TRX"];

function Chart({ candles, price, onHover }: { candles: Candle[]; price?: number; onHover: (candle: Candle | null) => void }) {
  const ordered = candles.slice(0, 90).reverse();
  const [hover, setHover] = useState<number | null>(null);
  const lows = ordered.map((c) => Number(c.low_price ?? c.trade_price));
  const highs = ordered.map((c) => Number(c.high_price ?? c.trade_price));
  const min = Math.min(...lows, price || Infinity); const max = Math.max(...highs, price || -Infinity); const span = Math.max(max - min, 1);
  const maxVol = Math.max(...ordered.map((c) => Number(c.candle_acc_trade_volume ?? 0)), 1);
  const px = (i: number) => 18 + (i / Math.max(ordered.length - 1, 1)) * 790;
  const py = (v: number) => 250 - ((v - min) / span) * 185;
  const ma = (period: number) => ordered.map((c, i) => i < period - 1 ? null : `${px(i)},${py(ordered.slice(i - period + 1, i + 1).reduce((s, x) => s + Number(x.trade_price), 0) / period)}`).filter(Boolean).join(" ");
  const pointer = (e: React.MouseEvent<SVGSVGElement>) => { const rect = e.currentTarget.getBoundingClientRect(); const index = Math.round(((e.clientX - rect.left) / rect.width) * (ordered.length - 1)); const safe = Math.max(0, Math.min(ordered.length - 1, index)); setHover(safe); onHover(ordered[safe] || null); };
  return <div className="relative h-full min-h-[330px] w-full overflow-hidden bg-[#0b0f14]">
    <svg viewBox="0 0 840 310" className="h-full w-full" preserveAspectRatio="none" onMouseMove={pointer} onMouseLeave={() => { setHover(null); onHover(null); }}>
      <g stroke="#222b35" strokeWidth="0.8">{[35, 85, 135, 185, 235, 285].map((y) => <line key={y} x1="0" x2="840" y1={y} y2={y} />)}{[105, 235, 365, 495, 625, 755].map((x) => <line key={x} y1="0" y2="280" x1={x} x2={x} />)}</g>
      {ordered.map((c, i) => { const o = Number(c.opening_price ?? c.trade_price); const cl = Number(c.trade_price); const hi = Number(c.high_price ?? Math.max(o, cl)); const lo = Number(c.low_price ?? Math.min(o, cl)); const up = cl >= o; const w = Math.max(3, 690 / Math.max(ordered.length, 1)); const volume = Number(c.candle_acc_trade_volume ?? 0) / maxVol * 34; return <g key={`${i}-${c.candle_date_time_kst}`}><line x1={px(i)} x2={px(i)} y1={py(hi)} y2={py(lo)} stroke={up ? "#3b82f6" : "#ef4444"} strokeWidth="1" /><rect x={px(i) - w / 2} y={Math.min(py(o), py(cl))} width={w} height={Math.max(1, Math.abs(py(o) - py(cl)))} fill={up ? "#3b82f6" : "#ef4444"} /><rect x={px(i) - w / 2} y={284 - volume} width={w} height={volume} fill={up ? "#3b82f666" : "#ef444466"} /></g>; })}
      <polyline points={ma(5)} fill="none" stroke="#f6c945" strokeWidth="1.6" /><polyline points={ma(20)} fill="none" stroke="#b66cff" strokeWidth="1.6" />
      {hover !== null && ordered[hover] && <><line x1={px(hover)} x2={px(hover)} y1="0" y2="280" stroke="#b7c3d0" strokeDasharray="3 3" /><line x1="0" x2="840" y1={py(Number(ordered[hover].trade_price))} y2={py(Number(ordered[hover].trade_price))} stroke="#b7c3d0" strokeDasharray="3 3" /><rect x={Math.min(px(hover) + 4, 690)} y="8" width="140" height="32" fill="#151d26" stroke="#526171" /><text x={Math.min(px(hover) + 10, 696)} y="21" fill="#f3f6f9" fontSize="10">{won(Number(ordered[hover].trade_price))}원</text><text x={Math.min(px(hover) + 10, 696)} y="33" fill="#98a7b8" fontSize="8">{ordered[hover].candle_date_time_kst?.slice(11, 16) || "실시간"}</text></>}
    </svg>
    <div className="pointer-events-none absolute bottom-1 left-3 text-[10px] text-zinc-500">파랑 상승 · 빨강 하락 · 노랑 5개 평균 · 보라 20개 평균 · 거래량</div>
  </div>;
}

export function TraderWorkspace({ mode }: { mode: "paper" | "live" }) {
  const [market, setMarket] = useState("KRW-BTC");
  const [markets, setMarkets] = useState<Market[]>(commonMarkets.map((m) => ({ market: m, korean_name: m.replace("KRW-", "") })));
  const [data, setData] = useState<Payload | null>(null); const [prices, setPrices] = useState<Record<string, number>>({}); const [flash, setFlash] = useState<string | null>(null);
  const [status, setStatus] = useState("실시간 연결 준비"); const [hovered, setHovered] = useState<Candle | null>(null); const [loopsByMarket, setLoopsByMarket] = useState<Record<string, LoopState>>({}); const [tickMetaByMarket, setTickMetaByMarket] = useState<Record<string, TickMeta>>({}); const [notice, setNotice] = useState("PAPER · JEV 판단 기반 실시간 이벤트 루프 대기"); const [auto, setAuto] = useState(mode === "paper"); const [busy, setBusy] = useState(false); const [side, setSide] = useState<"buy" | "sell">("buy"); const busyRef = useRef(false); const [liveAccount, setLiveAccount] = useState<AccountPayload | null>(null); const [eventSeq, setEventSeq] = useState(0);
  const [orderAmount, setOrderAmount] = useState("5000");
  const loop = loopsByMarket[market] || newLoopState();

  const load = useCallback(async (code: string) => { try { const r = await fetch(`/api/coin/market?market=${code}`, { cache: "no-store" }); const p = await r.json() as Payload; if (!p.ok) throw new Error(p.error || "[MARKET_DATA_ERROR] 업비트 캔들·호가 응답이 비어 있습니다"); setData(p); } catch (e) { setNotice(e instanceof Error ? e.message : "[MARKET_DATA_ERROR] 업비트 시세 조회에 실패했습니다"); } }, []);
  const refreshAccount = useCallback(async () => { if (mode !== "live") return; try { const r = await fetch("/api/coin/account", { cache: "no-store" }); const x = await r.json() as AccountPayload; if (!x.ok) throw new Error(x.error || "[LIVE_ACCOUNT_SYNC_ERROR] 실전 잔고 응답이 없습니다"); setLiveAccount(x); } catch (e) { setNotice(e instanceof Error ? e.message : "[LIVE_ACCOUNT_SYNC_ERROR] 실전 잔고 동기화에 실패했습니다"); } }, [mode]);
  useEffect(() => { void fetch("/api/coin/markets", { cache: "no-store" }).then((r) => r.json()).then((x) => { if (x.ok && x.markets?.length) { setMarkets(x.markets); setPrices(Object.fromEntries(x.markets.filter((item: Market) => typeof item.price === "number").map((item: Market) => [item.market, item.price as number]))); } }).catch(() => setNotice("[MARKET_LIST_ERROR] 업비트 코인 목록 조회에 실패했습니다")); }, []);
  useEffect(() => { void load(market); }, [load, market]);
  useEffect(() => { let stopped = false; let retry = 0; let stream: EventSource | null = null; let timer: ReturnType<typeof setTimeout> | null = null; const connect = () => { if (stopped) return; setStatus(retry ? `○ 실시간 재연결 중 ${retry}회` : "실시간 연결 중"); stream = new EventSource(`/api/coin/stream?market=${encodeURIComponent(market)}&codes=${encodeURIComponent(commonMarkets.join(","))}`); stream.onopen = () => { retry = 0; setStatus("● 실시간 중계 연결됨"); }; stream.onmessage = (e) => { try { const x = JSON.parse(e.data) as Record<string, unknown>; if (["relay_open", "relay_heartbeat"].includes(String(x.type))) return; if (x.type === "relay_error") { setNotice(`${String(x.code)} ${String(x.message)}`); return; } if (x.type === "ticker") { const code = String(x.code); const next = Number(x.trade_price); setPrices((p) => ({ ...p, [code]: next })); setFlash(code); window.setTimeout(() => setFlash((f) => f === code ? null : f), 260); if (code === market) { setData((p) => p ? { ...p, price: next } : p); setStatus(`● 실시간 수신 ${new Date().toLocaleTimeString("ko-KR")}`); setEventSeq((value) => value + 1); if (mode === "live") void refreshAccount(); } } else if (x.type === "orderbook" && x.code === market) { setData((p) => p ? { ...p, orderbook: { units: (x.orderbook_units as Unit[] | undefined)?.slice(0, 15) || [] } } : p); setEventSeq((value) => value + 1); } } catch { setNotice("[UPBIT_RELAY_PARSE_ERROR] 서버 중계 데이터 해석에 실패했습니다"); } }; stream.onerror = () => { if (stopped) return; setStatus("○ 서버 중계 재연결 대기"); setNotice("[UPBIT_RELAY_CONNECTION_RETRY] 서버 중계 연결이 끊겨 재연결합니다"); stream?.close(); retry = Math.min(retry + 1, 8); timer = setTimeout(connect, Math.min(1000 * 2 ** (retry - 1), 10000)); }; }; connect(); return () => { stopped = true; if (timer) clearTimeout(timer); stream?.close(); }; }, [market, mode, refreshAccount]);
  useEffect(() => { if (mode !== "live") return; void refreshAccount(); const timer = window.setInterval(() => void refreshAccount(), 2500); return () => window.clearInterval(timer); }, [mode, refreshAccount]);

  const runTick = useCallback(async () => { if (busyRef.current || !data?.price || !data.orderbook?.units?.[0] || mode !== "paper") return; busyRef.current = true; setBusy(true); const u = data.orderbook.units[0]; try { const r = await fetch("/api/coin/paper/tick", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ market, state: loop, input: { price: data.price, prices: data.candles?.map((c) => Number(c.trade_price)).reverse() || [], bestAsk: u.ask_price, bestBid: u.bid_price, askSize: u.ask_size, bidSize: u.bid_size, websocketHealthy: true, dataAgeMs: 0, allowedBuy: true, allowedSell: true, targetNotional: Number(orderAmount) || 5000 } }) }); const x = await r.json() as TickResponse; if (!x.ok || !x.result) throw new Error(x.error || `[${x.code || "JEV_PAPER_TICK_ERROR"}] 자동 판단 결과가 없습니다`); setLoopsByMarket((previous) => ({ ...previous, [market]: x.result!.state })); setTickMetaByMarket((previous) => ({ ...previous, [market]: { action: x.jev?.action || x.result!.action, provider: x.jev?.provider || x.result!.battery.provider, latencyMs: x.jev?.latencyMs || x.result!.battery.latencyMs, fills: x.result!.fills.length, orders: x.result!.orders.length, eventSeq } })); setNotice(`${x.jev?.provider === "JEV" ? "JEV" : "RULES_ONLY"} ${x.jev?.action || x.result.action} · 매수 ${(Number(x.jev?.probabilities?.BUY || x.result.battery.buyConfidence) * 100).toFixed(0)}% · 매도 ${(Number(x.jev?.probabilities?.SELL || x.result.battery.sellConfidence) * 100).toFixed(0)}% · ${x.result.fills.length ? `${x.result.fills.length}건 체결` : "지정가 대기"}${x.jev?.errorCode ? ` · [${x.jev.errorCode}]` : ""}`); } catch (e) { setNotice(e instanceof Error ? e.message : "[JEV_PAPER_TICK_ERROR] 자동 루프 실행에 실패했습니다"); } finally { busyRef.current = false; setBusy(false); } }, [data, eventSeq, loop, market, mode, orderAmount]);
  const runTickRef = useRef(runTick); useEffect(() => { runTickRef.current = runTick; }, [runTick]); useEffect(() => { if (!auto || mode !== "paper" || eventSeq === 0) return; const timer = window.setTimeout(() => void runTickRef.current(), 350); return () => window.clearTimeout(timer); }, [auto, mode, eventSeq]);

  const units = data?.orderbook?.units || []; const current = data?.price || prices[market]; const selected = hovered || data?.candles?.[0]; const spread = units[0] && current ? ((units[0].ask_price - units[0].bid_price) / current * 10000) : 0; const paperUnrealized = current ? loop.asset * current - loop.asset * loop.averageCost : 0; const displayedPnl = mode === "paper" ? loop.realizedPnl + paperUnrealized : Number(liveAccount?.pnl || 0);
  return <div className="flex h-[min(92vh,980px)] min-h-[660px] w-[calc(100vw-1rem)] max-w-[1700px] min-w-0 flex-col overflow-hidden border border-[#3b4652] bg-[#090c10] text-[12px] text-zinc-200 shadow-2xl">
    <header className="flex flex-wrap items-center gap-3 border-b border-[#2a333d] bg-[#11161c] px-3 py-2"><b className="text-[15px] text-white">{mode === "paper" ? "모의매매원" : "실제매매원"}</b><span className={mode === "paper" ? "text-amber-400" : "text-red-400"}>{mode === "paper" ? "PAPER" : "LIVE 잠금"}</span><span className="text-emerald-400">{status}</span>{mode === "paper" && <label className="ml-2 flex items-center gap-2 text-zinc-300"><input type="checkbox" checked={auto} onChange={(e) => setAuto(e.target.checked)} /> JEV 자동판단</label>}<span className="text-zinc-500">{mode === "paper" ? "실시간 지정가 체결 시뮬레이션" : "3단계 승인 전 실제 주문 차단"}</span><div className="ml-auto flex gap-1"><button className="border border-zinc-700 px-2 py-1">1분</button><button className="border border-zinc-700 px-2 py-1">5분</button><button className="border border-zinc-700 px-2 py-1">15분</button><button className="border border-zinc-700 px-2 py-1">지표</button><button className="border border-zinc-700 px-2 py-1">전체화면</button></div></header>
    <div className="grid min-h-0 flex-1 grid-cols-1 lg:grid-cols-[minmax(0,1fr)_300px_240px]">
      <section className="flex min-h-0 min-w-0 flex-col border-b border-[#2a333d] lg:border-b-0 lg:border-r"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-[#2a333d] px-3 py-2"><div><b className="text-white">{market.replace("KRW-", "")} / KRW</b><span className="ml-2 text-zinc-500">1분 · UPBIT</span>{selected && <span className="ml-3 text-sky-300">시 {won(Number(selected.opening_price))} 고 {won(Number(selected.high_price))} 저 {won(Number(selected.low_price))} 종 {won(Number(selected.trade_price))}</span>}</div><div className="text-right"><b className="text-base text-white">{won(current)}원</b><span className="ml-2 text-zinc-500">스프레드 {spread.toFixed(2)}bp</span></div></div><div className="flex min-h-0 flex-1"><div className="hidden w-9 flex-col items-center gap-5 border-r border-[#2a333d] py-4 text-zinc-500 sm:flex"><span>＋</span><span>╱</span><span>⌁</span><span>♢</span><span>⌕</span><span>Ｔ</span><span>◉</span><span>＋</span></div><div className="min-h-[330px] min-w-0 flex-1"><Chart candles={data?.candles || []} price={current} onHover={setHovered} /></div></div><div className="flex gap-4 border-t border-[#2a333d] px-3 py-2 text-zinc-500"><span>30일</span><span>5일</span><span>1일</span><span className="ml-auto">UTC+9</span><span>％</span><span>로그</span><span className="text-sky-400">자동</span></div></section>
      <section className="flex min-h-0 flex-col border-b border-[#2a333d] lg:border-b-0 lg:border-r"><div className="flex items-center justify-between border-b border-[#2a333d] px-3 py-2"><span className="text-zinc-300">호가 · {market}</span><span className="text-zinc-600">매도 / 매수</span></div><div className="grid grid-cols-2 px-2 py-1 text-right text-[10px] text-zinc-600"><span>매도 수량 · 가격</span><span>가격 · 매수 수량</span></div><div className="min-h-0 flex-1 overflow-auto">{units.map((u, i) => <div key={`${u.ask_price}-${i}`} className="grid grid-cols-2 border-b border-[#171d23] text-right"><span className="bg-red-950/25 px-2 py-1 text-red-300">{u.ask_size.toFixed(4)}<br /><b>{won(u.ask_price)}</b></span><span className="bg-blue-950/25 px-2 py-1 text-sky-300"><b>{won(u.bid_price)}</b><br />{u.bid_size.toFixed(4)}</span></div>)}</div><div className="border-t border-[#2a333d] p-3"><div className="mb-2 flex gap-1"><button onClick={() => setSide("buy")} className={`flex-1 border px-2 py-2 ${side === "buy" ? "border-emerald-500 bg-emerald-950/40 text-emerald-300" : "border-zinc-700 text-zinc-500"}`}>매수</button><button onClick={() => setSide("sell")} className={`flex-1 border px-2 py-2 ${side === "sell" ? "border-red-500 bg-red-950/40 text-red-300" : "border-zinc-700 text-zinc-500"}`}>매도</button></div><div className="grid grid-cols-[70px_1fr] gap-2 text-zinc-500"><span>주문금액</span><input value={orderAmount} onChange={(e) => setOrderAmount(e.target.value.replace(/[^0-9]/g, ""))} className="border border-zinc-700 bg-[#0b0f14] px-2 py-1 text-right text-white outline-none" /><span>가격</span><span className="border border-zinc-800 px-2 py-1 text-right text-zinc-300">{won(current)}원</span></div><button onClick={() => void runTick()} disabled={busy || mode !== "paper"} className={`mt-2 w-full border px-2 py-2 ${side === "buy" ? "border-emerald-700 text-emerald-300" : "border-red-700 text-red-300"}`}>{busy ? "JEV 판단 중" : `JEV ${side === "buy" ? "매수" : "매도"} 판단 실행`}</button></div><div className="border-t border-[#2a333d] p-3 text-zinc-500">JEV 상태: <b className="text-amber-300">{loop.tick ? `${loop.tick}틱 · ${loop.resting.length}개 대기` : "대기"}</b><br />체결 {loop.fills.length}건 · 실현손익 {won(loop.realizedPnl)}원{tickMetaByMarket[market] && <><br />최근 판단 {tickMetaByMarket[market].provider} · {tickMetaByMarket[market].latencyMs}ms · 이벤트 #{tickMetaByMarket[market].eventSeq}</>}</div></section>
      <section className="flex min-h-0 flex-col"><div className="border-b border-[#2a333d] px-3 py-2 text-zinc-300">코인목록 · 현재가 · 거래대금</div><div className="grid grid-cols-[1fr_75px_60px] px-2 py-1 text-[10px] text-zinc-600"><span>코인</span><span className="text-right">현재가</span><span className="text-right">변동</span></div><div className="min-h-0 flex-1 overflow-auto">{markets.map((m) => { const p = prices[m.market]; return <button key={m.market} onClick={() => setMarket(m.market)} className={`grid w-full grid-cols-[1fr_75px_60px] border-b border-[#171d23] px-2 py-2 text-left hover:bg-[#1a222b] ${market === m.market ? "bg-[#202b36]" : ""} ${flash === m.market ? "animate-pulse bg-amber-950/50" : ""}`}><span><b className="block text-zinc-200">{m.market.replace("KRW-", "")}</b><small className="text-zinc-600">{m.korean_name}</small></span><span className="text-right text-zinc-200">{p ? won(p) : "-"}</span><span className={`text-right ${Number(m.change) >= 0 ? "text-red-400" : "text-blue-400"}`}>{m.change == null ? "-" : `${Number(m.change) >= 0 ? "+" : ""}${(Number(m.change) * 100).toFixed(2)}%`}</span></button>; })}</div><div className="border-t border-[#2a333d] p-3 text-zinc-500">자동 루프: <b className={auto ? "text-emerald-300" : "text-zinc-500"}>{auto ? "ON · 업비트 실시간 이벤트마다 PAPER 판단" : "OFF"}</b><br />데이터는 업비트 WebSocket 중계 기준</div></section>
    </div><div className="flex flex-wrap items-center gap-4 border-t border-[#2a333d] px-3 py-2 text-zinc-400"><span>{mode === "paper" ? "PAPER 현금" : "LIVE 현금"} <b className="text-white">{won(mode === "paper" ? loop.cash : liveAccount?.cash)}원</b></span><span>{mode === "paper" ? "PAPER 보유평가" : "LIVE 매매자산"} <b className="text-white">{won(mode === "paper" ? loop.asset * Number(current || 0) : liveAccount?.tradingValue)}원</b></span><span>실시간 손익 <b className={displayedPnl >= 0 ? "text-emerald-300" : "text-red-300"}>{displayedPnl >= 0 ? "+" : "-"}{won(Math.abs(displayedPnl))}원</b></span><span className="ml-auto text-[10px]">{mode === "paper" ? "체결·평가손익은 업비트 틱마다 즉시 반영" : `실전 잔고 동기화 ${liveAccount?.updatedAt ? new Date(liveAccount.updatedAt).toLocaleTimeString("ko-KR") : "대기"}`}</span></div><div className={`border-t px-3 py-2 ${notice.includes("[") ? "border-red-900 bg-red-950/20 text-red-300" : "border-[#2a333d] text-zinc-400"}`}>{notice}</div>{mode === "live" && <div className="border-t border-red-900 bg-red-950/20 px-3 py-2 text-red-300">실제 주문 잠금: 승인관리·리스크관리·블랙 최종승인과 서버 게이트를 모두 통과하기 전에는 주문 API를 호출하지 않습니다</div>}</div>;
}
