import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {TradingAnalytics,marketSample,tradeContext} from '../../services/trading/analytics.mjs';
import {Engine} from '../../services/trading/core/engine.mjs';
import {Store} from '../../services/trading/core/store.mjs';
import {newLedger,applyFill,D} from '../../services/trading/core/core.mjs';
import {PolicyStore} from '../../services/trading/policies.mjs';
import {defaultPolicy,evidenceQuestions} from '../../services/trading/core/evidence.mjs';
function fixture(t,mode='paper'){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'analytics-test-'));const feed={symbol:'KRW-TEST',clockVerified:true,book:{timestamp:Date.now(),receivedAt:Date.now(),orderbook_units:[{ask_price:10000,bid_price:9999,ask_size:100,bid_size:100}]},bookHistory:[],candles:Array.from({length:25},()=>({close:10000})),trades:Array.from({length:15},(_,i)=>({trade_timestamp:Date.now()-i*100,trade_price:10000,trade_volume:1,ask_bid:'BID'})),markets:[],activity:{snapshot:()=>({})}};
 const e=new Engine(feed,new Store(path.join(dir,mode)));clearInterval(e.timer);e.mode=mode;e[mode]=newLedger(1000000,'KRW-TEST',mode);e.config.strategyEnabled=0;e.config.maxPositionKrw=500000;e.config.cooldownSeconds=0;e.armed=true;e.jevVerified=true;e.running=true;
 const a=new TradingAnalytics(path.join(dir,'analytics'));e.analytics=a;e.askJev=async()=>({id:'fixture-decision',model:'test-only',stateAsOf:Date.now(),answers:Object.fromEntries(Object.keys(evidenceQuestions(e.policy,Number(e.ledger().quantity)>0)).map(k=>[k,{choice:'supported',probabilities:{supported:.9,unknown:.05,opposed:.05}}]))});
 t.after(()=>{clearInterval(e.timer);a.close();});return{e,a,dir,feed};
}
test('actual PAPER engine: buy/sell evidence, windows, net profit, report and all filters',async t=>{
 const {e,a,feed,dir}=fixture(t);const base=Date.now();for(let at=base-60000;at<=base;at+=1000){feed.book.timestamp=at;a.observe(marketSample(feed,at));}feed.book.timestamp=Date.now();await e.analyze();assert.equal(e.ledger().history.length,1);assert.equal(e.ledger().history[0].side,'buy');
 const bought=e.ledger().history[0];assert.ok(bought.analytics.evidence.some(x=>x.id==='entry_0'&&x.version===1));const originalText=bought.analytics.evidence[0].text;
 e.policy.rules=e.policy.rules.map(r=>({...r,text:r.text+' 새 버전',version:2}));feed.book.orderbook_units[0].bid_price=9800;feed.book.orderbook_units[0].ask_price=9801;feed.book.timestamp=Date.now();await e.analyze();assert.equal(e.ledger().history.length,2);const sold=e.ledger().history[1];assert.equal(sold.analytics.evidence[0].version,2);assert.equal(bought.analytics.evidence[0].text,originalText);
 for(let at=base+1000;at<=sold.at+62000;at+=1000){feed.book.timestamp=at;a.observe(marketSample(feed,at));}a.clock=()=>sold.at+63000;
 const q=a.query({from:base-1000,to:a.clock(),outcome:'loss',mode:'paper',market:'KRW-TEST',staff:'Jev 매수근거',rule:'entry_0',version:1,minReturn:-100,maxReturn:0,buyReason:'근거 종합',sellReason:'매도근거',cause:'jev'});assert.equal(q.total,1);assert.ok(q.rows[0].realized<0);assert.ok(Math.abs(q.rows[0].realized-Number(sold.realized))<1e-7);assert.equal(q.rows[0].quantity,0);
 const detail=a.detail(q.rows[0].id);assert.equal(detail.fills.length,2);assert.ok(detail.fills.every(f=>f.window.count>=120));assert.ok(detail.samples.length<detail.fills.reduce((n,f)=>n+f.window.count,0));assert.ok(detail.fills.every(f=>f.window.status==='완료'));
 const report=a.report({from:base-1000,to:a.clock()});assert.equal(report.losses,1);assert.ok(report.byEvidence.some(x=>x.key.includes('entry_0 v1')));assert.equal(a.status().state,'대기중');const summary=a.summary('paper');assert.ok(Math.abs(summary.net-(summary.profit-summary.loss))<1e-8);
 const count=a.status().fills;a.sync(e);a.sync(e);assert.equal(a.status().fills,count);const restored=new TradingAnalytics(path.join(dir,'analytics'));assert.equal(restored.query({from:0,to:a.clock()}).total,1);assert.equal(restored.detail(q.rows[0].id).fills[0].context.evidence[0].text,originalText);restored.close();
 assert.equal(a.query({from:0,to:a.clock(),version:99,rule:'entry_0'}).total,0);assert.equal(a.query({from:0,to:a.clock(),outcome:'profit'}).total,0);assert.throws(()=>a.query({limit:501}));assert.throws(()=>a.query({mode:'oops'}));assert.throws(()=>a.detail('sql injection'));
});
test('live fake broker reconcile records original pending evidence once; no exchange request',async t=>{
 const {e,a,feed}=fixture(t,'live');e.broker.verified=true;e.broker.chance=async()=>({bid_fee:'.0005',ask_fee:'.0005',bid_account:{balance:'1000000'},ask_account:{balance:'100',locked:'0'},market:{state:'active',bid:{min_total:'5000'},ask:{min_total:'5000'}}});e.broker.send=async()=>({uuid:'fake-only'});e.broker.find=async()=>({state:'done',executed_volume:'1',paid_fee:'5',trades:[{volume:'1',funds:'10000',price:'10000'}]});await e.analyze();const original=e.live.pending.analytics;assert.ok(original.evidence.length);e.policy.rules=[];await e.reconcile();await e.reconcile();assert.equal(a.status().fills,1);assert.deepEqual(e.live.history[0].analytics,original);assert.equal(a.query({mode:'paper'}).total,0);assert.equal(a.query({mode:'live'}).total,1);
});
test('hard stop retains cause and risk settings before AI decision is cleared',t=>{const {e}=fixture(t);applyFill(e.paper,'buy',{quantity:'1',funds:'10000',fee:'5',price:10000});e.safety.request('절대 손실 한도 도달','hard_stop');assert.equal(e.paper.exitIntent.analytics.cause,'hard_stop');assert.equal(e.paper.exitIntent.analytics.limits.stopLossPct,.7);assert.equal(e.paper.exitIntent.analytics.decision,null);assert.deepEqual(e.paper.exitIntent.analytics.evidence,[]);});
test('manual tracking records manual provenance; no stale Jev attribution',async t=>{const {e,a,feed}=fixture(t);e.running=false;e.tracker.state={id:'fixture-tracker',active:true,generation:e.generation,mode:'paper',market:feed.symbol,ledgerId:e.paper.id,side:'buy',targetFunds:'10000',targetQuantity:'0',filled:'0',funds:'0',fees:'0',attempts:0};await e.tracker.attempt(D(10000));assert.equal(e.paper.history[0].analytics.cause,'manual');assert.deepEqual(e.paper.history[0].analytics.evidence,[]);assert.equal(a.status().fills,1);});
test('legacy import is idempotent and does not invent evidence or change ledger',t=>{const {e,a}=fixture(t);applyFill(e.paper,'buy',{quantity:'1',funds:'10000',fee:'5',price:10000});const before=JSON.stringify(e.paper);a.sync(e);a.sync(e);assert.equal(JSON.stringify(e.paper),before);const q=a.query();assert.equal(q.total,1);assert.equal(a.detail(q.rows[0].id).fills[0].cause,'legacy_unknown');});
test('partial sells form one roundtrip and preserve exact ledger net and fees',t=>{const {e,a}=fixture(t);for(const [side,q,funds,fee]of [['buy','2','20000','10'],['sell','1','10500','5.25'],['sell','1','9500','4.75']]){applyFill(e.paper,side,{quantity:q,funds,fee,price:Number(funds)/Number(q)},{analytics:tradeContext(e)});a.sync(e);}const rows=a.query().rows;assert.equal(rows.length,1);assert.equal(rows[0].realized,-20);assert.equal(rows[0].buy_fees+rows[0].sell_fees,20);assert.equal(a.summary('paper').net,-20);});
test('storage capacity failure never rolls back a fill and reports degraded collection',t=>{const {e,a}=fixture(t);a.maxBytes=1;applyFill(e.paper,'buy',{quantity:'1',funds:'10000',fee:'5',price:10000},{analytics:tradeContext(e)});e.save();assert.equal(e.paper.history.length,1);assert.equal(a.status().fills,1);assert.equal(a.status().collection,'이상');});
test('public market whitelist excludes credentials, balances and arbitrary input',t=>{const {e,feed}=fixture(t);e.chance={secret:'SENSITIVE',bid_account:{balance:'SECRET_BALANCE'}};feed.book.secret='TOKEN';feed.trades[0].apikey='TOKEN';const s=JSON.stringify(tradeContext(e));assert.ok(!s.includes('SENSITIVE'));assert.ok(!s.includes('SECRET_BALANCE'));assert.ok(!s.includes('TOKEN'));});
test('rule version is server owned and survives deletion/reintroduction',t=>{const {e,dir}=fixture(t);e.running=false;const w={engine:e,controller:{busy:false,recovering:false}},p=new PolicyStore(dir,{paper:w,live:w});let v=p.get('coin').policy;const first=structuredClone(v.rules[0]);v.rules[0].version=999;v.rules[0].text+=' changed';p.update('coin',v,v.revision);assert.equal(p.get('coin').policy.rules[0].version,2);v=p.get('coin').policy;v={...v,rules:v.rules.filter(r=>r.id!==first.id)};p.update('coin',v,v.revision);v=p.get('coin').policy;p.update('coin',{...v,rules:[...v.rules,first]},v.revision);assert.equal(p.get('coin').policy.rules.at(-1).version,3);});

test('post-event feed survives symbol switch, expires and reports busy only during pending window',t=>{const {e,a,feed}=fixture(t);let connected=0,stopped=0;const at=Date.now();a.feedFactory=()=>({generation:0,connect(){connected++;},stop(){stopped++;}});applyFill(e.paper,'buy',{quantity:'1',funds:'10000',fee:'5',price:10000},{analytics:tradeContext(e)});a.sync(e);assert.equal(a.status().state,'업무중');a.retain(feed,'KRW-OTHER');assert.equal(connected,1);assert.equal(a.tails.get('KRW-TEST').feed.symbol,'KRW-TEST');a.retain(feed,'KRW-OTHER');assert.equal(connected,1);a.sample(at+62000);assert.equal(stopped,1);assert.equal(a.tails.size,0);a.clock=()=>at+62000;assert.equal(a.status().state,'대기중');});

test('one satoshi residual is still open, never reported as a closed roundtrip',t=>{const {e,a}=fixture(t);applyFill(e.paper,'buy',{quantity:'1',funds:'10000',fee:'5',price:10000});a.sync(e);applyFill(e.paper,'sell',{quantity:'.99999999',funds:'10000',fee:'5',price:10000});a.sync(e);assert.ok(D(e.paper.quantity).eq('0.00000001'));assert.equal(a.query().rows[0].closed,null);});
