import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {defaultPolicy,validatePolicy,evidenceQuestions,evidenceDecision,investmentPlan} from '../../services/trading/core/evidence.mjs';
import {PolicyStore} from '../../services/trading/policies.mjs';
import {Engine} from '../../services/trading/core/engine.mjs';
import {newLedger} from '../../services/trading/core/core.mjs';
import {askJev,questions} from '../../services/trading/core/jev.mjs';
const answer=(qs)=>Object.fromEntries(Object.entries(qs).map(([k,q])=>{if(q.type==='noul')return[k,{type:q.type,noul:0.1}];const keys=q.type==='score'?q.criteria.map((_,i)=>String(i)):Object.keys(q.criteria);const chosen=keys.includes('supported')?'supported':keys.includes('up')?'up':keys[0];return[k,{type:q.type,choice:chosen,score:0,confidence:0.9,probabilities:Object.fromEntries(keys.map(x=>[x,x===chosen?0.9:0.1/(keys.length-1)]))}];}));
function setup(t,mode){let saved;const store={load:()=>null,save:s=>{saved=structuredClone(s)},log:()=>{}};const feed={symbol:'KRW-A',clockVerified:true,book:{timestamp:Date.now(),receivedAt:Date.now(),orderbook_units:[{ask_price:10000,bid_price:9999,ask_size:100,bid_size:100}]},candles:Array.from({length:25},()=>({close:10000})),trades:Array.from({length:15},(_,i)=>({trade_timestamp:Date.now()-i*200,trade_price:10000,trade_volume:1,ask_bid:'BID'})),markets:[{market:'KRW-B',korean_name:'후보B'}],activity:{snapshot:()=>({fullWindow:true,ready:true,asOf:Date.now(),recentKrw:1e8,growthRatio:2,returnPct:1})},select:async function(m){this.symbol=m;},snapshot:()=>({})};const e=new Engine(feed,store);clearInterval(e.timer);e.mode=mode;e[mode]=newLedger(1000000,'KRW-A',mode);e.config.strategyEnabled=0;e.config.maxPositionKrw=500000;e.armed=true;e.broker.verified=true;e.jevVerified=true;e.jevKey='fixture';e.running=true;e.liveTest={market:'KRW-A',at:Date.now()};if(mode==='live')e.live.exchangeBaseline='2';const chance={market:{state:'active',bid:{min_total:'5000'},ask:{min_total:'5000'}},bid_fee:'.0005',ask_fee:'.0005',bid_account:{balance:'1000000'},ask_account:{balance:'2',locked:'0'}};e.chance=chance;e.broker.chance=async()=>chance;e.broker.test=async()=>({});e.askJev=async(k,state)=>({id:'fixture',stateAsOf:Date.now(),at:Date.now(),market:feed.symbol,answers:answer({...questions(),...evidenceQuestions(e.policy,Number(e.ledger().quantity)>0)})});t.after(()=>clearInterval(e.timer));return{e,feed,chance,store,saved:()=>saved};}
test('invalid, duplicate, excessive and malformed policy is rejected; empty list is a deliberate hold',()=>{const p=defaultPolicy();assert.throws(()=>validatePolicy({...p,rules:[p.rules[0],p.rules[0]]}));assert.throws(()=>validatePolicy({...p,sizing:{minPct:50,maxPct:10,riskPct:.25}}));assert.equal(evidenceDecision({...p,rules:[]},{},false).side,'hold');});
test('added/deleted evidence changes actual model request and unknown blocks entry',async()=>{const p=defaultPolicy();p.rules.push({id:'extra',category:'entry',text:'뉴스에 대한 실제 데이터 확인'});let payload;await askJev('fixture',{market:{market:'KRW-A',asOf:Date.now()},botPosition:{quantity:0},evidencePolicy:p},'',async(u,o)=>{payload=JSON.parse(o.body);return {ok:true,json:async()=>({model:'fixture',answers:answer(payload.questions)})};});assert.equal(payload.questions.rule_extra.instructions.criterion,p.rules.at(-1).text);const a=answer(evidenceQuestions(p,false));a.rule_extra={choice:'unknown',probabilities:{unknown:.9,supported:.05,opposed:.05}};assert.equal(evidenceDecision(p,a,false).side,'hold');p.rules=p.rules.filter(x=>x.id!=='extra');assert.equal(evidenceQuestions(p,false).rule_extra,undefined);assert.equal(evidenceDecision(p,a,false).side,'buy');});
test('missing dynamic answer never becomes a buy signal',async()=>{await assert.rejects(askJev('fixture',{market:{asOf:Date.now()},evidencePolicy:defaultPolicy()},'',async()=>({ok:true,json:async()=>({answers:answer(questions())})})),/응답 형식/);});
for(const mode of ['paper','live']){
 test(mode+': latest leader switch preserves interval, running flag and balance baseline',async t=>{const{e,feed}=setup(t,mode);e.lastAnalysis=Date.now();const last=e.lastAnalysis;await e.scanMarket();assert.equal(feed.symbol,'KRW-B');assert.equal(e.ledger().market,'KRW-B');assert.equal(e.running,true);assert.equal(e.lastAnalysis,last);if(mode==='live')assert.equal(e.live.exchangeBaseline,'2');});
 for(const blocker of ['holding','pending','tracking','exit'])test(mode+': '+blocker+' blocks leader switch',async t=>{const{e,feed}=setup(t,mode);if(blocker==='holding')e.ledger().quantity='.00000001';if(blocker==='pending')e.ledger().pending={};if(blocker==='tracking')e.tracker.state={active:true};if(blocker==='exit')e.ledger().exitIntent={phase:'verifying'};await e.scanMarket();assert.equal(feed.symbol,'KRW-A');});
 test(mode+': stale response after policy change cannot order',async t=>{const{e}=setup(t,mode);let release;const old=e.askJev;e.askJev=(...args)=>new Promise(r=>{release=()=>old(...args).then(r)});let n=0;e.order=async()=>n++;const pending=e.analyze();e.generation++;release();await pending;assert.equal(n,0);});
 test(mode+': actual automatic order uses ratio rather than fixed 10000',async t=>{const{e,feed}=setup(t,mode);e.config.maxDrawdownPct=10;e.config.dailyLossKrw=100000;e.action=evidenceDecision(e.policy,answer(evidenceQuestions(e.policy,false)),false);e.decision={id:'fixture',stateAsOf:Date.now()};let sent;e.broker.send=async(p,guard)=>{guard();sent=p;return{uuid:p.identifier}};e.reconcile=async()=>{};await e.order('buy',10000,'100','test',true,'fixture');assert.ok(e.investment.amount>10000);if(mode==='live')assert.equal(Number(sent.price),e.investment.amount);else assert.ok(Number(e.paper.quantity)*10000>10000);});
}
test('live stop during candidate preflight never switches or re-arms',async t=>{const{e,feed,chance}=setup(t,'live');let release;e.broker.chance=()=>new Promise(r=>release=r);const p=e.scanMarket();e.stop();release(chance);await assert.rejects(p,/정지/);assert.equal(feed.symbol,'KRW-A');assert.equal(e.armed,false);});
test('live balance mismatch blocks selection and failed target test never sends orders',async t=>{const{e,feed,chance}=setup(t,'live');e.live.exchangeBaseline='3';await assert.rejects(e.scanMarket(),/불일치/);e.live.exchangeBaseline='2';e.lastScan=0;e.broker.test=async()=>{throw Error('test rejected')};await assert.rejects(e.scanMarket(),/rejected/);assert.equal(feed.symbol,'KRW-A');});
test('investment is capped by allocation, position, fee and risk and cannot round up to minimum',()=>{const p=defaultPolicy(),a=evidenceDecision(p,answer(evidenceQuestions(p,false)),false),l=newLedger(1e6,'KRW-A'),f={bid:10000,visibleAskKrw:1e8},c={feePct:.05,maxPositionKrw:50000,dailyLossKrw:10000,maxDrawdownPct:3,stopLossPct:.7,slippageBps:2};assert.equal(investmentPlan(p,a,l,f,c).amount,50000);l.cash='4000';assert.equal(investmentPlan(p,a,l,f,c).amount,0);});
test('atomic policy file applies both modes, survives restart, rejects stale editors and in-flight orders',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'evidence-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const workers=Object.fromEntries(['paper','live'].map(mode=>{const{e}=setup(t,mode);return[mode,{engine:e,controller:{busy:false,recovering:false}}]}));const store=new PolicyStore(dir,workers);const p=store.get('coin').policy;p.rules=p.rules.filter(r=>r.category!=='trend');store.update('coin',p,0);assert.equal(workers.paper.engine.policy.revision,1);assert.equal(workers.live.engine.policy.revision,1);assert.throws(()=>store.update('coin',p,0),/다른 창/);workers.live.engine.orderBusy=true;assert.throws(()=>store.update('coin',p,1),/처리 중/);assert.equal(new PolicyStore(dir,workers).get('coin').policy.revision,1);assert.deepEqual(store.update('stock',defaultPolicy(),0).appliedModes,[]);});
