import test from 'node:test';
import assert from 'node:assert/strict';
import {MarketScanner,scannerConfig} from '../../services/trading/core/scanner.mjs';
import {Engine} from '../../services/trading/core/engine.mjs';
import {newLedger} from '../../services/trading/core/core.mjs';
import {evidenceQuestions} from '../../services/trading/core/evidence.mjs';
function fixture(){let now=1800000000000;const start=now,s=new MarketScanner({clock:()=>now});s.source={clockOffsetMs:0};for(const symbol of ['KRW-A','KRW-B'])s.states.set(symbol,{symbol,name:symbol,buckets:[],trades:[],tradeIds:new Set(),candles:[],bookHistory:[],state:'MONITOR',since:now,firstObservedAt:null});function frame(i){now=start+i*1000;for(const symbol of s.states.keys()){const price=10000+i*.1;s.observe({type:'orderbook',code:symbol,timestamp:now,orderbook_units:[{ask_price:price+.1,bid_price:price,bid_size:100,ask_size:10}]});s.observe({type:'trade',code:symbol,sequential_id:i,trade_timestamp:now,trade_price:price,trade_volume:1,ask_bid:'BID'});}s.refresh(now);}for(let i=0;i<125;i++)frame(i);return{s,frame,now:()=>now,start};}
test('rolling context persists for multiple markets; ready candidates have pre-promotion observations',()=>{const{s}=fixture();for(const x of s.states.values()){assert.ok(x.buckets.length>=120);assert.equal(x.state,'ENTRY_READY');assert.ok(x.firstObservedAt<x.candidateAt);assert.ok(x.readyAt>x.firstObservedAt);}const a=s.context('KRW-A');s.pick('KRW-B','paper');assert.equal(s.context('KRW-A').firstObservedAt,a.firstObservedAt);assert.equal(s.context('KRW-A').readyAt,a.readyAt);});
test('one shared pending lease, cooldown and event dedup prevent Jev storm',()=>{const{s,frame}=fixture();const l=s.acquire('paper','KRW-A',{periodic:true});assert.ok(l);assert.equal(s.acquire('live','KRW-B',{periodic:true}),null);s.release(l);assert.equal(s.acquire('paper','KRW-A',{periodic:true}),null);frame(140);assert.ok(s.acquire('live','KRW-B',{periodic:true}));assert.equal(s.callCount,2);});
test('stale data, late entry and insufficient context cannot acquire',()=>{const{s,frame,now}=fixture();s.states.get('KRW-A').metrics.lateRisk=true;assert.equal(s.acquire('paper','KRW-A',{periodic:true}),null);assert.equal(s.acquire('paper','KRW-B',{periodic:true,now:now()+5000}),null);frame(126);s.states.get('KRW-B').state='WARMING';assert.equal(s.acquire('paper','KRW-B',{periodic:true}),null);});
test('duplicate and out-of-order trades do not double count; rolling memory bounded',()=>{const{s,now}=fixture();const x=s.states.get('KRW-A'),before=x.trades.length;s.observe({type:'trade',code:'KRW-A',sequential_id:124,trade_timestamp:now(),trade_price:10000,trade_volume:1,ask_bid:'BID'});assert.equal(x.trades.length,before);assert.ok(x.buckets.length<=121);assert.ok(x.trades.length<=3000);});
test('invalid scanner configuration is rejected; independent weights can be tuned',()=>{assert.throws(()=>scannerConfig({eventCooldownSeconds:0}));assert.throws(()=>scannerConfig({candidateScore:99,readyScore:50}));assert.throws(()=>scannerConfig({trendWeight:0,flowWeight:0,liquidityWeight:0}));assert.equal(scannerConfig({trendWeight:2}).trendWeight,2);});
function engine(t,mode='paper'){
 const now=Date.now(),feed={symbol:'KRW-A',clockVerified:true,clockOffsetMs:0,book:{timestamp:now,receivedAt:now,orderbook_units:[{ask_price:10000,bid_price:9999,ask_size:100,bid_size:100}]},candles:Array.from({length:40},(_,i)=>({time:now-(40-i)*60000,open:10000,high:10001,low:9998,close:10000,volume:10})),trades:Array.from({length:15},(_,i)=>({trade_timestamp:now-i*200,trade_price:10000,trade_volume:1,ask_bid:'BID'})),markets:[],select:async function(symbol){this.symbol=symbol;},snapshot:()=>({})};
 const e=new Engine(feed,{load:()=>null,save:()=>{},log:()=>{}});clearInterval(e.timer);t.after(()=>clearInterval(e.timer));e.mode=mode;e[mode]=newLedger(1e6,'KRW-A',mode);e.running=true;e.judgmentRunning=true;e.jevVerified=true;e.config.strategyEnabled=0;e.config.maxPositionKrw=50000;e.lastAnalysis=Date.now();e.armed=true;e.broker.verified=true;if(mode==='live')e.live.exchangeBaseline='0';e.broker.chance=async()=>({market:{state:'active',bid:{min_total:'5000'},ask:{min_total:'5000'}},bid_fee:'.0005',ask_fee:'.0005',bid_account:{balance:'1000000'},ask_account:{balance:'0',locked:'0'}});e.broker.test=async()=>({});
 let calls=0;e.askJev=async()=>{calls++;return{id:'test-'+calls,stateAsOf:Date.now(),answers:Object.fromEntries(Object.keys(evidenceQuestions(e.policy,Number(e.ledger().quantity)>0)).map(k=>[k,{choice:'supported',probabilities:{supported:.9,opposed:.05,unknown:.05}}]))};};return{e,feed,calls:()=>calls};
}
for(const mode of ['paper','live'])test(mode+': candidate switch retains preloaded context, holding/pending prevents switch',async t=>{const{e,feed}=engine(t,mode);const{s}=fixture();s.pick=()=>({market:'KRW-B',name:'B'});feed.scanner=s;e.ledger().quantity='.00000001';await e.scanMarket();assert.equal(feed.symbol,'KRW-A');e.ledger().quantity='0';e.ledger().pending={};await e.scanMarket();assert.equal(feed.symbol,'KRW-A');e.ledger().pending=null;await e.scanMarket();assert.equal(feed.symbol,'KRW-B');assert.equal(s.states.get('KRW-A').buckets.length,121);});
test('event-driven actual PAPER analysis executes before 60s, records trace, closes then next context survives',async t=>{const{e,feed,calls}=engine(t);const{s}=fixture();feed.scanner=s;let leaseReleased=false;const ctx={market:'KRW-A',state:'ENTRY_READY',metrics:{lateRisk:false},asOf:Date.now(),firstObservedAt:Date.now()-120000,readyAt:Date.now()-3000};s.acquire=()=>({symbol:'KRW-A',context:ctx,reason:'fixture event'});s.release=()=>{leaseReleased=true};s.context=()=>ctx;await e.analyzeCandidate();assert.equal(calls(),1);assert.ok(Number(e.paper.quantity)>0);assert.ok(leaseReleased);assert.ok(e.paper.history[0].analytics.scanner.jevStartedAt);assert.ok(Date.now()-e.scannerTrace.jevStartedAt<5000);feed.book.timestamp=Date.now();await new Promise(r=>setTimeout(r,1100));feed.book.timestamp=Date.now();ctx.asOf=Date.now();await e.analyzeCandidate();assert.equal(Number(e.paper.quantity),0);assert.equal(e.paper.history.length,2);assert.ok(s.states.get('KRW-B').buckets.length>=120);});
test('stop while Jev pending fences automatic order and releases lease',async t=>{const{e,feed}=engine(t);let release,released=false;feed.scanner={acquire:()=>({context:{},reason:'test'}),release:()=>{released=true},context:()=>({state:'ENTRY_READY',metrics:{}})};e.askJev=()=>new Promise(r=>release=r);const task=e.analyzeCandidate();e.stop();release({id:'late',stateAsOf:Date.now(),answers:{}});await task;assert.equal(e.paper.history.length,0);assert.ok(released);});
