import WebSocket from '../../../public/trading/core/web-socket.mjs';
import {randomUUID} from 'node:crypto';
import {updateCandles,fromRest} from './candles.mjs';
const clamp=x=>Math.max(0,Math.min(1,x));
export const scannerDefaults={trendWeight:1,flowWeight:1,liquidityWeight:1,warmingScore:50,candidateScore:65,readyScore:72,eventCooldownSeconds:30,globalCooldownSeconds:15,stableSeconds:2,switchMargin:5,maxRiseBps:150,maxVwapGapBps:80,maxEntryRiseBps:70,maxEntryVwapGapBps:40,maxFastRiseBps:25,minBuyShare:0.55,minTurnoverGrowth:1.1};
export function scannerConfig(input={}){
 const out={...scannerDefaults,...input};
 for(const k of Object.keys(scannerDefaults))if(!Number.isFinite(out[k]))throw Error('시장 감시 설정: '+k+' 숫자를 확인하세요.');
 if(['trendWeight','flowWeight','liquidityWeight'].some(k=>out[k]<0||out[k]>10)||out.trendWeight+out.flowWeight+out.liquidityWeight<=0)throw Error('시장 감시 비중: 0~10, 합계는 0보다 커야 합니다.');
 if(!(out.warmingScore>=0&&out.warmingScore<=out.candidateScore&&out.candidateScore<=out.readyScore&&out.readyScore<=100))throw Error('시장 감시 점수: 예비 ≤ 후보 ≤ 정밀판단, 0~100 범위');
 if(out.eventCooldownSeconds<10||out.eventCooldownSeconds>600||out.globalCooldownSeconds<5||out.globalCooldownSeconds>60||out.stableSeconds<1||out.stableSeconds>30||out.switchMargin<0||out.switchMargin>30||out.maxRiseBps<20||out.maxRiseBps>1000||out.maxVwapGapBps<10||out.maxVwapGapBps>500||out.maxEntryRiseBps<10||out.maxEntryRiseBps>out.maxRiseBps||out.maxEntryVwapGapBps<5||out.maxEntryVwapGapBps>out.maxVwapGapBps||out.maxFastRiseBps<5||out.maxFastRiseBps>200||out.minBuyShare<0.5||out.minBuyShare>0.9||out.minTurnoverGrowth<0.5||out.minTurnoverGrowth>5)throw Error('시장 감시 설정 범위 오류: 재판단 10~600초, 전체 간격 5~60초, 유지 1~30초, 전환차 0~30점, 급등/진입이격/매수세/거래대금 기준을 확인하세요.');
 return Object.fromEntries(Object.keys(scannerDefaults).map(k=>[k,out[k]]));
}
// One public stream shared by PAPER and LIVE. No keys, account data or order methods.
export class MarketScanner{
 constructor({clock=Date.now}={}){this.clock=clock;this.states=new Map();this.markets=[];this.listeners=new Set();this.status='연결 대기';this.messages=0;this.bytes=0;this.config=scannerConfig();this.pending=new Map();this.calls=new Map();this.lastCall=0;this.callCount=0;this.events=[];this.closed=false;}
 configure(value){this.config=scannerConfig(value);}
 start(feed){if(this.source)return;this.source=feed;this.markets=feed.markets;for(const m of this.markets)this.states.set(m.market,{symbol:m.market,name:m.korean_name,excluded:m.market_warning==='CAUTION'||m.market_event?.warning===true,buckets:[],trades:[],tradeIds:new Set(),candles:[],bookHistory:[],state:'MONITOR',since:this.clock(),firstObservedAt:null});this.connect();this.timer=setInterval(()=>{this.refresh();void this.seed();},500);this.timer.unref?.();}
 connect(){if(this.closed)return;const ws=this.ws=new WebSocket('wss://api.upbit.com/websocket/v1');let alive=this.clock();ws.on('open',()=>{ws.send(JSON.stringify([{ticket:randomUUID()},{type:'trade',codes:this.markets.map(m=>m.market),is_only_realtime:true},{type:'orderbook',codes:this.markets.map(m=>m.market)}]));this.status='전체 시장 연결';});ws.on('message',raw=>{try{this.bytes+=raw.length;this.messages++;const m=JSON.parse(raw.toString());if(m.error)throw Error(m.error.name);alive=this.clock();this.observe(m);}catch{this.status='시장 감시 메시지 오류';}});ws.on('error',()=>{this.status='시장 감시 연결 오류';});const heartbeat=setInterval(()=>{if(ws.readyState===WebSocket.OPEN){ws.ping();if(this.clock()-alive>15000)ws.terminate();}},5000);ws.on('close',()=>{clearInterval(heartbeat);if(!this.closed){this.status='시장 감시 재연결 대기';for(const s of this.states.values()){s.book=null;s.buckets=[];s.trades=[];s.tradeIds.clear();s.firstObservedAt=null;s.state='MONITOR';s.readyAt=null;}this.retry=setTimeout(()=>this.connect(),3000);}});}
 observe(m){const s=this.states.get(m.code);if(!s)return;const now=this.clock(),offset=this.source?.clockOffsetMs||0;if(m.type==='orderbook'){if(!m.orderbook_units?.length||!Number.isFinite(m.timestamp))return;const stamp=m.timestamp+offset;if(s.book&&stamp<s.book.timestamp)return;s.book={...m,sourceTimestamp:m.timestamp,timestamp:stamp,receivedAt:now};const rows=m.orderbook_units.slice(0,10);s.bookHistory.push({at:stamp,bidDepth:rows.reduce((n,x)=>n+x.bid_price*x.bid_size,0),askDepth:rows.reduce((n,x)=>n+x.ask_price*x.ask_size,0)});s.bookHistory=s.bookHistory.filter(x=>x.at>=now-15000).slice(-200);}
 else if(m.type==='trade'){const at=m.trade_timestamp+offset;if(!Number.isFinite(at)||at<now-120000||at>now+2000||!(m.trade_price>0&&m.trade_volume>0)||!['BID','ASK'].includes(m.ask_bid))return;const id=String(m.sequential_id);if(s.tradeIds.has(id))return;s.tradeIds.add(id);const t={code:m.code,sequential_id:m.sequential_id,trade_timestamp:at,sourceTradeTimestamp:m.trade_timestamp,trade_price:m.trade_price,trade_volume:m.trade_volume,ask_bid:m.ask_bid};s.trades.push(t);s.trades.sort((a,b)=>a.trade_timestamp-b.trade_timestamp);while(s.trades.length>3000||s.trades[0]?.trade_timestamp<now-120000){s.tradeIds.delete(String(s.trades.shift().sequential_id));}const sec=Math.floor(at/1000)*1000;let b=s.buckets.find(x=>x.at===sec);if(!b){b={at:sec,open:m.trade_price,close:m.trade_price,high:m.trade_price,low:m.trade_price,volume:0,funds:0,buy:0,count:0,lastAt:at,firstAt:at};s.buckets.push(b);s.buckets.sort((a,b)=>a.at-b.at);}if(at>=b.lastAt){b.close=m.trade_price;b.lastAt=at;}if(at<=b.firstAt){b.open=m.trade_price;b.firstAt=at;}b.high=Math.max(b.high,m.trade_price);b.low=Math.min(b.low,m.trade_price);b.volume+=m.trade_volume;b.funds+=m.trade_volume*m.trade_price;b.buy+=m.ask_bid==='BID'?m.trade_volume*m.trade_price:0;b.count++;s.buckets=s.buckets.filter(x=>x.at>=now-120000).slice(-121);s.firstObservedAt??=now;s.lastTradeAt=at;updateCandles(s.candles,t,1);s.candles=s.candles.slice(-200);}
 for(const fn of this.listeners)fn(s,m.type);
 }
 refresh(now=this.clock()){for(const s of this.states.values()){const cfg=this.config,b=s.book?.orderbook_units;if(!b?.length||now-s.book.receivedAt>3000||now-s.book.timestamp>3000||s.book.timestamp>now+2000||s.excluded||!s.firstObservedAt){s.state='MONITOR';s.readyAt=null;continue;}const rows=s.buckets.filter(x=>x.at>now-60000&&x.at<=now),old=s.buckets.filter(x=>x.at>now-120000&&x.at<=now-60000);if(!rows.length){s.state='MONITOR';s.readyAt=null;continue;}const sum=(rs,k)=>rs.reduce((n,x)=>n+x[k],0),mid=(b[0].ask_price+b[0].bid_price)/2,first=rows[0],last=rows.at(-1),funds=sum(rows,'funds'),oldFunds=sum(old,'funds'),growth=old.length&&oldFunds>0?funds/oldFunds:null;
 const fast=rows.filter(x=>x.at>now-5000),prior=rows.filter(x=>x.at<=now-5000&&x.at>now-10000),ret=rs=>rs.length>1?(rs.at(-1).close/rs[0].open-1)*10000:0,fastReturn=ret(fast),priorReturn=ret(prior),returnBps=(last.close/first.open-1)*10000,acceleration=fastReturn-priorReturn,bid=b.slice(0,10).reduce((n,x)=>n+x.bid_price*x.bid_size,0),ask=b.slice(0,10).reduce((n,x)=>n+x.ask_price*x.ask_size,0),imbalance=(bid-ask)/Math.max(1,bid+ask),spread=(b[0].ask_price-b[0].bid_price)/mid*10000,vwap=funds/Math.max(1e-20,sum(rows,'volume')),buy=funds?sum(rows,'buy')/funds:null,oldBuy=oldFunds?sum(old,'buy')/oldFunds:null,buyDelta=buy!==null&&oldBuy!==null?buy-oldBuy:null,priorHigh=rows.length>1?Math.max(...rows.slice(0,-1).map(x=>x.high)):null,high=Math.max(...rows.map(x=>x.high)),low=Math.min(...rows.map(x=>x.low)),wick=(high-last.close)/Math.max(high-low,1e-10),oldBook=s.bookHistory.findLast(x=>x.at<=now-5000),wallGrowth=oldBook?.askDepth>0?ask/oldBook.askDepth-1:0,vwapGapBps=(mid/vwap-1)*10000;
 const timing=clamp(1-Math.abs(returnBps-15)/Math.max(60,cfg.maxRiseBps)),flowGrowth=growth===null?.5:clamp(growth/2),buyImprovement=buyDelta===null?.5:clamp(.5+buyDelta*2),earlyMomentum=clamp(.5+acceleration/40);
 const groups={trend:clamp(timing*.7+earlyMomentum*.3),flow:clamp((buy??.5)*.45+flowGrowth*.35+buyImprovement*.2),liquidity:clamp((imbalance+1)/2)*clamp(1-spread/50)};const score=100*(groups.trend*cfg.trendWeight+groups.flow*cfg.flowWeight+groups.liquidity*cfg.liquidityWeight)/(cfg.trendWeight+cfg.flowWeight+cfg.liquidityWeight);
 const lateRisk=returnBps>cfg.maxRiseBps||vwapGapBps>cfg.maxVwapGapBps||(wick>.7&&buy<.45)||wallGrowth>2;
 const entryTooLate=returnBps>cfg.maxEntryRiseBps||vwapGapBps>cfg.maxEntryVwapGapBps||fastReturn>cfg.maxFastRiseBps;
 const fullWindow=now-s.firstObservedAt>=60000,flowReady=(buy??0)>=cfg.minBuyShare&&(growth===null||growth>=cfg.minTurnoverGrowth),leadSignal=(growth!==null&&growth>=cfg.minTurnoverGrowth)||(buyDelta!==null&&buyDelta>=.08)||imbalance>=.2,entryConfirm=fullWindow&&flowReady&&leadSignal&&imbalance>=-.05&&spread<=25&&acceleration>=-10&&!entryTooLate&&!lateRisk;
 const prev=s.state;const next=lateRisk||entryTooLate?'EXTENDED':score>=cfg.readyScore&&entryConfirm?'ENTRY_READY':score>=cfg.candidateScore&&fullWindow?'SETUP':score>=cfg.warmingScore?'PRE_SETUP':'MONITOR';
 s.metrics={mid,returnBps,fastReturnBps:fastReturn,acceleration,volume:sum(rows,'volume'),turnover:funds,growth,buyShare:buy,buyShareDelta:buyDelta,spreadBps:spread,imbalance,bidDepthKrw:bid,askDepthKrw:ask,vwap,vwapGapBps,priorHigh,high,low,upperWick:wick,askDepthGrowth:wallGrowth,lateRisk,entryTooLate,entryConfirm,fullWindow,contextSeconds:Math.min(120,(now-s.firstObservedAt)/1000),groups};s.score=score;s.asOf=now;
 const triggers=[growth!==null&&growth>=cfg.minTurnoverGrowth?'거래대금 선행 증가':null,buyDelta!==null&&buyDelta>=.08?'매수 체결비중 상승':null,imbalance>=.2?'매수 호가 개선':null,acceleration>3&&fastReturn<=cfg.maxFastRiseBps?'초입 재가속':null,priorHigh&&mid>priorHigh&&!entryTooLate?'초기 고점 돌파':null].filter(Boolean);const signature=triggers.join('|');if(signature!==s.signature){s.signature=signature;s.eventAt=now;s.eventId=s.symbol+':'+now+':'+signature;}s.triggers=triggers;
 if(next!==prev){s.state=next;s.since=now;if(next==='PRE_SETUP')s.strengthObservedAt=now;if(next==='SETUP'||next==='ENTRY_READY')s.candidateAt??=now;s.readyAt=next==='ENTRY_READY'?now:null;this.events.push({market:s.symbol,at:now,from:prev,to:next,score,trigger:signature});this.events=this.events.slice(-1000);}
 }}
 ranked(now=this.clock()){return [...this.states.values()].filter(s=>!s.excluded&&s.metrics&&now-s.asOf<2000&&s.book&&now-s.book.receivedAt<=3000).sort((a,b)=>(b.score||0)-(a.score||0));}
 candidates(){return this.ranked().map(s=>({market:s.symbol,name:s.name,score:s.score,state:s.state,activity:{recentKrw:s.metrics.turnover},...this.context(s.symbol)}));}
 context(symbol){const s=this.states.get(symbol);if(!s)return null;return {market:symbol,score:s.score??null,state:s.state,metrics:s.metrics||null,triggers:s.triggers||[],eventId:s.eventId||null,firstObservedAt:s.firstObservedAt,strengthObservedAt:s.strengthObservedAt||null,candidateAt:s.candidateAt||null,readyAt:s.readyAt||null,asOf:s.asOf||null};}
 pick(current,mode,now=this.clock()){const ready=this.ranked(now).filter(s=>s.state==='ENTRY_READY'&&now-s.since>=this.config.stableSeconds*1000&&!this.pending.has(s.symbol)&&now-(this.calls.get(mode+':'+s.symbol)?.at||0)>=this.config.eventCooldownSeconds*1000);let best=ready[0];const same=ready.find(s=>s.symbol===current);if(same&&best&&best.score-same.score<this.config.switchMargin)best=same;return best?{market:best.symbol,name:best.name,score:best.score}:null;}
 acquire(mode,symbol,{periodic=false,now=this.clock()}={}){const s=this.states.get(symbol),key=mode+':'+symbol,last=this.calls.get(key);if(!s||s.state!=='ENTRY_READY'||s.metrics.lateRisk||now-s.asOf>2000||!s.book||now-s.book.receivedAt>3000||now-s.since<this.config.stableSeconds*1000||this.pending.size||now-this.lastCall<this.config.globalCooldownSeconds*1000||now-(last?.at||0)<this.config.eventCooldownSeconds*1000||(!periodic&&(!s.triggers.length||last?.eventId===s.eventId)))return null;const lease={key,symbol,at:now,eventId:s.eventId,reason:periodic?'정기 후보 판단':s.triggers.join(' · '),context:this.context(symbol)};this.pending.set(symbol,lease);this.lastCall=now;this.calls.set(key,{at:now,eventId:s.eventId});this.callCount++;return lease;}
 release(lease){if(this.pending.get(lease.symbol)===lease)this.pending.delete(lease.symbol);}
 attach(feed){feed.scanner=this;this.listeners.add((s,type)=>{if(feed.symbol!==s.symbol)return;feed.book=s.book;feed.bookHistory=s.bookHistory;feed.trades=s.trades;if(s.candles.length>=35)feed.signalCandles=s.candles;if(type==='trade'){const t=s.trades.at(-1);if(t)updateCandles(feed.candles,t,feed.units);}feed.lastMessage=this.clock();feed.status=this.status;if(type==='orderbook'||type==='trade')feed.onRiskChange?.();feed.onChange();});}
 hydrate(feed){const s=this.states.get(feed.symbol);if(!s)return;feed.book=s.book;feed.bookHistory=s.bookHistory;feed.trades=s.trades;if(s.candles.length>=35)feed.signalCandles=s.candles;}
 async seed(){if(this.seeding||!this.source)return;const s=this.ranked().filter(s=>s.state!=='EXTENDED').slice(0,8).find(s=>s.candles.length<35&&this.clock()-(s.seedAttempt||0)>60000);if(!s)return;this.seeding=true;s.seedAttempt=this.clock();try{const rows=await this.source.rest('/v1/candles/minutes/1?market='+s.symbol+'&count=60');s.candles=fromRest(rows,s.trades,1);}catch{this.seedError='후보 1분봉 준비 실패 · 재시도 대기';}finally{this.seeding=false;}}
 snapshot(){const rows=this.candidates();return {version:3,status:this.status,total:this.states.size,observed:[...this.states.values()].filter(s=>s.firstObservedAt).length,strong:rows.filter(s=>['SETUP','ENTRY_READY'].includes(s.state)).length,candidates:rows.slice(0,10),messages:this.messages,bytes:this.bytes,jevCalls:this.callCount,pending:this.pending.size,config:this.config,note:'선행예측형 V3 연구 점수이며 수익 확률 아님. PRE_SETUP→SETUP→ENTRY_READY만 진입 검토, EXTENDED는 추격 차단.'};}
 stop(){this.closed=true;clearInterval(this.timer);clearTimeout(this.retry);this.ws?.close();this.listeners.clear();}
}
